/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "csm_secc.h"

#define UNUSED(X) ((void)(X))

static inline uint64 reverse_byte_order(uint64 x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

#define CANID_SeccInformation_80030001h (0x80030001)
#define CANID_EvEvccId_80030002h (0x80030002)
#define CANID_EvChargingService_80030003h (0x80030003)
#define CANID_EvDcChargingStatus_80030004h (0x80030004)
#define CANID_EvDcChargingVariable_80030005h (0x80030005)
#define CANID_EvDcChargeParameter_80030006h (0x80030006)
#define CANID_EvDcMinimumChargeParam_80030007h (0x80030007)
#define CANID_EvDcDischargeParam_80030008h (0x80030008)
#define CANID_EvAcChargeParam_80030009h (0x80030009)
#define CANID_EvAcPresentActivePower_8003000ah (0x8003000a)
#define CANID_EvAcPresentReactivePower_8003000bh (0x8003000b)
#define CANID_EvAcMaximumChargePower_8003000ch (0x8003000c)
#define CANID_EvAcMinimumChargePower_8003000dh (0x8003000d)
#define CANID_EvAcMaximumDischargePower_8003000eh (0x8003000e)
#define CANID_EvAcMinimumDischargePower_8003000fh (0x8003000f)
#define CANID_EvTargetEnergy_80030010h (0x80030010)
#define CANID_EvEnergyRequestLimit_80030011h (0x80030011)
#define CANID_EvDisplayPresentStatus_8003001ah (0x8003001a)
#define CANID_EvDisplayTargetSoc_8003001bh (0x8003001b)
#define CANID_EvDisplayMaximumSoc_8003001ch (0x8003001c)
#define CANID_EvDisplayMinimumSoc_8003001dh (0x8003001d)
#define CANID_KVasEvBatteryHeader_80030101h (0x80030101)
#define CANID_KVasEvBatteryData_80030102h (0x80030102)
#define CANID_SeccDateTime_800301f1h (0x800301f1)

const static int enum_to_id[] = {
  CANID_SeccInformation_80030001h,
  CANID_EvEvccId_80030002h,
  CANID_EvChargingService_80030003h,
  CANID_EvDcChargingStatus_80030004h,
  CANID_EvDcChargingVariable_80030005h,
  CANID_EvDcChargeParameter_80030006h,
  CANID_EvDcMinimumChargeParam_80030007h,
  CANID_EvDcDischargeParam_80030008h,
  CANID_EvAcChargeParam_80030009h,
  CANID_EvAcPresentActivePower_8003000ah,
  CANID_EvAcPresentReactivePower_8003000bh,
  CANID_EvAcMaximumChargePower_8003000ch,
  CANID_EvAcMinimumChargePower_8003000dh,
  CANID_EvAcMaximumDischargePower_8003000eh,
  CANID_EvAcMinimumDischargePower_8003000fh,
  CANID_EvTargetEnergy_80030010h,
  CANID_EvEnergyRequestLimit_80030011h,
  CANID_EvDisplayPresentStatus_8003001ah,
  CANID_EvDisplayTargetSoc_8003001bh,
  CANID_EvDisplayMaximumSoc_8003001ch,
  CANID_EvDisplayMinimumSoc_8003001dh,
  CANID_KVasEvBatteryHeader_80030101h,
  CANID_KVasEvBatteryData_80030102h,
  CANID_SeccDateTime_800301f1h,
};

int candb_csm_secc_get_can_id(csm_secc_msg_types msg_type) {
  return (msg_type < csm_secc_msg_max_count) ? enum_to_id[msg_type] : 0;
}

static int pack_csm_secc_SeccInformation_0x80030001(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* PwmDutyCycle: start-bit 40, length 10, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->SeccInformation.PwmDutyCycle)) & 0x3ff;
	x <<= 40; 
	i |= x;
	/* SeccStatusCode: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccInformation.SeccStatusCode)) & 0xff;
	x <<= 8; 
	i |= x;
	/* SeccErrorCode: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccInformation.SeccErrorCode)) & 0xff;
	x <<= 16; 
	i |= x;
	/* SeccSWVersion: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccInformation.SeccSWVersion)) & 0xff;
	x <<= 24; 
	i |= x;
	/* ProximityVoltage: start-bit 32, length 8, endianess intel, scaling 0.1, offset 0 */
	x = ((uint8)(o->SeccInformation.ProximityVoltage)) & 0xff;
	x <<= 32; 
	i |= x;
	/* PwmVoltage: start-bit 56, length 8, endianess intel, scaling 0.1, offset 0 */
	x = ((uint8)(o->SeccInformation.PwmVoltage)) & 0xff;
	x <<= 56; 
	i |= x;
	/* SeccProtocol: start-bit 52, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccInformation.SeccProtocol)) & 0xf;
	x <<= 52; 
	i |= x;
	/* SeccReady: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccInformation.SeccReady)) & 0x1;
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_SeccInformation_0x80030001(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* PwmDutyCycle: start-bit 40, length 10, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 40) & 0x3ff;
	o->SeccInformation.PwmDutyCycle = x;
	/* SeccStatusCode: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->SeccInformation.SeccStatusCode = x;
	/* SeccErrorCode: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xff;
	o->SeccInformation.SeccErrorCode = x;
	/* SeccSWVersion: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0xff;
	o->SeccInformation.SeccSWVersion = x;
	/* ProximityVoltage: start-bit 32, length 8, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xff;
	o->SeccInformation.ProximityVoltage = x;
	/* PwmVoltage: start-bit 56, length 8, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 56) & 0xff;
	o->SeccInformation.PwmVoltage = x;
	/* SeccProtocol: start-bit 52, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 52) & 0xf;
	o->SeccInformation.SeccProtocol = x;
	/* SeccReady: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = i & 0x1;
	o->SeccInformation.SeccReady = x;
	return 0;
}

int candb_decode_csm_secc_PwmDutyCycle_0x80030001(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->SeccInformation.PwmDutyCycle);
	rval *= 0.1;
	if (rval <= 102.3) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_PwmDutyCycle_0x80030001(can_csm_secc_t *o, float64 in) {
	o->SeccInformation.PwmDutyCycle = 0;
	if (in > 102.3)
		return -1;
	in *= 10;
	o->SeccInformation.PwmDutyCycle = in;
	return 0;
}

int candb_decode_csm_secc_SeccStatusCode_0x80030001(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccInformation.SeccStatusCode);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_SeccStatusCode_0x80030001(can_csm_secc_t *o, uint8 in) {
	o->SeccInformation.SeccStatusCode = in;
	return 0;
}

int candb_decode_csm_secc_SeccErrorCode_0x80030001(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccInformation.SeccErrorCode);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_SeccErrorCode_0x80030001(can_csm_secc_t *o, uint8 in) {
	o->SeccInformation.SeccErrorCode = in;
	return 0;
}

int candb_decode_csm_secc_SeccSWVersion_0x80030001(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccInformation.SeccSWVersion);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_SeccSWVersion_0x80030001(can_csm_secc_t *o, uint8 in) {
	o->SeccInformation.SeccSWVersion = in;
	return 0;
}

int candb_decode_csm_secc_ProximityVoltage_0x80030001(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->SeccInformation.ProximityVoltage);
	rval *= 0.1;
	if (rval <= 25.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_ProximityVoltage_0x80030001(can_csm_secc_t *o, float64 in) {
	o->SeccInformation.ProximityVoltage = 0;
	if (in > 25.5)
		return -1;
	in *= 10;
	o->SeccInformation.ProximityVoltage = in;
	return 0;
}

int candb_decode_csm_secc_PwmVoltage_0x80030001(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->SeccInformation.PwmVoltage);
	rval *= 0.1;
	if ((rval >= -12.8) && (rval <= 12.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_PwmVoltage_0x80030001(can_csm_secc_t *o, float64 in) {
	o->SeccInformation.PwmVoltage = 0;
	if (in < -12.8)
		return -1;
	if (in > 12.7)
		return -1;
	in *= 10;
	o->SeccInformation.PwmVoltage = in;
	return 0;
}

int candb_decode_csm_secc_SeccProtocol_0x80030001(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccInformation.SeccProtocol);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_SeccProtocol_0x80030001(can_csm_secc_t *o, uint8 in) {
	o->SeccInformation.SeccProtocol = in;
	return 0;
}

int candb_decode_csm_secc_SeccReady_0x80030001(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccInformation.SeccReady);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_SeccReady_0x80030001(can_csm_secc_t *o, uint8 in) {
	o->SeccInformation.SeccReady = in;
	return 0;
}

static int pack_csm_secc_EvEvccId_0x80030002(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EvccId: start-bit 0, length 48, endianess intel, scaling 1, offset 0 */
	x = ((uint64)(o->EvEvccId.EvccId)) & 0xffffffffffff;
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvEvccId_0x80030002(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EvccId: start-bit 0, length 48, endianess intel, scaling 1, offset 0 */
	x = i & 0xffffffffffff;
	o->EvEvccId.EvccId = x;
	return 0;
}

int candb_decode_csm_secc_EvccId_0x80030002(const can_csm_secc_t *o, uint64 *out) {
	uint64 rval = (uint64)(o->EvEvccId.EvccId);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_EvccId_0x80030002(can_csm_secc_t *o, uint64 in) {
	o->EvEvccId.EvccId = in;
	return 0;
}

static int pack_csm_secc_EvChargingService_0x80030003(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* DepartureTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32)(o->EvChargingService.DepartureTime)) & 0xffffffff;
	x <<= 32; 
	i |= x;
	/* MaxSupportPoint: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->EvChargingService.MaxSupportPoint)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* RequestedEnergyTransferType: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvChargingService.RequestedEnergyTransferType)) & 0xff;
	x <<= 8; 
	i |= x;
	/* BPT_ChannelSelection: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvChargingService.BPT_ChannelSelection)) & 0xf;
	x <<= 4; 
	i |= x;
	/* SelectedPaymentOption: start-bit 0, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvChargingService.SelectedPaymentOption)) & 0x3;
	i |= x;
	/* Iso20ControlMode: start-bit 2, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvChargingService.Iso20ControlMode)) & 0x3;
	x <<= 2; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvChargingService_0x80030003(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* DepartureTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->EvChargingService.DepartureTime = x;
	/* MaxSupportPoint: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvChargingService.MaxSupportPoint = x;
	/* RequestedEnergyTransferType: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->EvChargingService.RequestedEnergyTransferType = x;
	/* BPT_ChannelSelection: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->EvChargingService.BPT_ChannelSelection = x;
	/* SelectedPaymentOption: start-bit 0, length 2, endianess intel, scaling 1, offset 0 */
	x = i & 0x3;
	o->EvChargingService.SelectedPaymentOption = x;
	/* Iso20ControlMode: start-bit 2, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 2) & 0x3;
	o->EvChargingService.Iso20ControlMode = x;
	return 0;
}

int candb_decode_csm_secc_DepartureTime_0x80030003(const can_csm_secc_t *o, uint32 *out) {
	uint32 rval = (uint32)(o->EvChargingService.DepartureTime);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_DepartureTime_0x80030003(can_csm_secc_t *o, uint32 in) {
	o->EvChargingService.DepartureTime = in;
	return 0;
}

int candb_decode_csm_secc_MaxSupportPoint_0x80030003(const can_csm_secc_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->EvChargingService.MaxSupportPoint);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_MaxSupportPoint_0x80030003(can_csm_secc_t *o, uint16 in) {
	o->EvChargingService.MaxSupportPoint = in;
	return 0;
}

int candb_decode_csm_secc_RequestedEnergyTransferType_0x80030003(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvChargingService.RequestedEnergyTransferType);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_RequestedEnergyTransferType_0x80030003(can_csm_secc_t *o, uint8 in) {
	o->EvChargingService.RequestedEnergyTransferType = in;
	return 0;
}

int candb_decode_csm_secc_BPT_ChannelSelection_0x80030003(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvChargingService.BPT_ChannelSelection);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_BPT_ChannelSelection_0x80030003(can_csm_secc_t *o, uint8 in) {
	o->EvChargingService.BPT_ChannelSelection = in;
	return 0;
}

int candb_decode_csm_secc_SelectedPaymentOption_0x80030003(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvChargingService.SelectedPaymentOption);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_SelectedPaymentOption_0x80030003(can_csm_secc_t *o, uint8 in) {
	o->EvChargingService.SelectedPaymentOption = in;
	return 0;
}

int candb_decode_csm_secc_Iso20ControlMode_0x80030003(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvChargingService.Iso20ControlMode);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Iso20ControlMode_0x80030003(can_csm_secc_t *o, uint8 in) {
	o->EvChargingService.Iso20ControlMode = in;
	return 0;
}

static int pack_csm_secc_EvDcChargingStatus_0x80030004(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* RemainingTimeFullSoc: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->EvDcChargingStatus.RemainingTimeFullSoc)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* RemainingTimeBulkSoc: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->EvDcChargingStatus.RemainingTimeBulkSoc)) & 0xffff;
	x <<= 48; 
	i |= x;
	/* EVErrorCode: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDcChargingStatus.EVErrorCode)) & 0xff;
	x <<= 16; 
	i |= x;
	/* RESS_Soc: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDcChargingStatus.RESS_Soc)) & 0xff;
	x <<= 24; 
	i |= x;
	/* BulkChargingComplete: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDcChargingStatus.BulkChargingComplete)) & 0x1;
	x <<= 8; 
	i |= x;
	/* FullChargingComplete: start-bit 9, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDcChargingStatus.FullChargingComplete)) & 0x1;
	x <<= 9; 
	i |= x;
	/* EvReady: start-bit 10, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDcChargingStatus.EvReady)) & 0x1;
	x <<= 10; 
	i |= x;
	/* EvCabinConditioning: start-bit 11, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDcChargingStatus.EvCabinConditioning)) & 0x1;
	x <<= 11; 
	i |= x;
	/* EvRessConditioning: start-bit 12, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDcChargingStatus.EvRessConditioning)) & 0x1;
	x <<= 12; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvDcChargingStatus_0x80030004(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* RemainingTimeFullSoc: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvDcChargingStatus.RemainingTimeFullSoc = x;
	/* RemainingTimeBulkSoc: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->EvDcChargingStatus.RemainingTimeBulkSoc = x;
	/* EVErrorCode: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xff;
	o->EvDcChargingStatus.EVErrorCode = x;
	/* RESS_Soc: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0xff;
	o->EvDcChargingStatus.RESS_Soc = x;
	/* BulkChargingComplete: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0x1;
	o->EvDcChargingStatus.BulkChargingComplete = x;
	/* FullChargingComplete: start-bit 9, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 9) & 0x1;
	o->EvDcChargingStatus.FullChargingComplete = x;
	/* EvReady: start-bit 10, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 10) & 0x1;
	o->EvDcChargingStatus.EvReady = x;
	/* EvCabinConditioning: start-bit 11, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 11) & 0x1;
	o->EvDcChargingStatus.EvCabinConditioning = x;
	/* EvRessConditioning: start-bit 12, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 12) & 0x1;
	o->EvDcChargingStatus.EvRessConditioning = x;
	return 0;
}

int candb_decode_csm_secc_RemainingTimeFullSoc_0x80030004(const can_csm_secc_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->EvDcChargingStatus.RemainingTimeFullSoc);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_RemainingTimeFullSoc_0x80030004(can_csm_secc_t *o, uint16 in) {
	o->EvDcChargingStatus.RemainingTimeFullSoc = in;
	return 0;
}

int candb_decode_csm_secc_RemainingTimeBulkSoc_0x80030004(const can_csm_secc_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->EvDcChargingStatus.RemainingTimeBulkSoc);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_RemainingTimeBulkSoc_0x80030004(can_csm_secc_t *o, uint16 in) {
	o->EvDcChargingStatus.RemainingTimeBulkSoc = in;
	return 0;
}

int candb_decode_csm_secc_EVErrorCode_0x80030004(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDcChargingStatus.EVErrorCode);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_EVErrorCode_0x80030004(can_csm_secc_t *o, uint8 in) {
	o->EvDcChargingStatus.EVErrorCode = in;
	return 0;
}

int candb_decode_csm_secc_RESS_Soc_0x80030004(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDcChargingStatus.RESS_Soc);
	if (rval <= 100) {
		*out = rval;
		return 0;
	} else {
		*out = (uint8)0;
		return -1;
	}
}

int candb_encode_csm_secc_RESS_Soc_0x80030004(can_csm_secc_t *o, uint8 in) {
	o->EvDcChargingStatus.RESS_Soc = 0;
	if (in > 100)
		return -1;
	o->EvDcChargingStatus.RESS_Soc = in;
	return 0;
}

int candb_decode_csm_secc_BulkChargingComplete_0x80030004(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDcChargingStatus.BulkChargingComplete);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_BulkChargingComplete_0x80030004(can_csm_secc_t *o, uint8 in) {
	o->EvDcChargingStatus.BulkChargingComplete = in;
	return 0;
}

int candb_decode_csm_secc_FullChargingComplete_0x80030004(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDcChargingStatus.FullChargingComplete);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_FullChargingComplete_0x80030004(can_csm_secc_t *o, uint8 in) {
	o->EvDcChargingStatus.FullChargingComplete = in;
	return 0;
}

int candb_decode_csm_secc_EvReady_0x80030004(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDcChargingStatus.EvReady);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_EvReady_0x80030004(can_csm_secc_t *o, uint8 in) {
	o->EvDcChargingStatus.EvReady = in;
	return 0;
}

int candb_decode_csm_secc_EvCabinConditioning_0x80030004(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDcChargingStatus.EvCabinConditioning);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_EvCabinConditioning_0x80030004(can_csm_secc_t *o, uint8 in) {
	o->EvDcChargingStatus.EvCabinConditioning = in;
	return 0;
}

int candb_decode_csm_secc_EvRessConditioning_0x80030004(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDcChargingStatus.EvRessConditioning);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_EvRessConditioning_0x80030004(can_csm_secc_t *o, uint8 in) {
	o->EvDcChargingStatus.EvRessConditioning = in;
	return 0;
}

static int pack_csm_secc_EvDcChargingVariable_0x80030005(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVTargetCurrent: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcChargingVariable.EVTargetCurrent)) & 0xffff;
	i |= x;
	/* EVTargetVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcChargingVariable.EVTargetVoltage)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMaximumCurrentLimit: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcChargingVariable.EVMaximumCurrentLimit)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* EVMaximumVoltageLimit: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcChargingVariable.EVMaximumVoltageLimit)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvDcChargingVariable_0x80030005(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVTargetCurrent: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvDcChargingVariable.EVTargetCurrent = x;
	/* EVTargetVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvDcChargingVariable.EVTargetVoltage = x;
	/* EVMaximumCurrentLimit: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvDcChargingVariable.EVMaximumCurrentLimit = x;
	/* EVMaximumVoltageLimit: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->EvDcChargingVariable.EVMaximumVoltageLimit = x;
	return 0;
}

int candb_decode_csm_secc_EVTargetCurrent_0x80030005(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcChargingVariable.EVTargetCurrent);
	rval *= 0.1;
	if (rval <= 4000) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVTargetCurrent_0x80030005(can_csm_secc_t *o, float64 in) {
	o->EvDcChargingVariable.EVTargetCurrent = 0;
	if (in > 4000)
		return -1;
	in *= 10;
	o->EvDcChargingVariable.EVTargetCurrent = in;
	return 0;
}

int candb_decode_csm_secc_EVTargetVoltage_0x80030005(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcChargingVariable.EVTargetVoltage);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVTargetVoltage_0x80030005(can_csm_secc_t *o, float64 in) {
	o->EvDcChargingVariable.EVTargetVoltage = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvDcChargingVariable.EVTargetVoltage = in;
	return 0;
}

int candb_decode_csm_secc_EVMaximumCurrentLimit_0x80030005(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcChargingVariable.EVMaximumCurrentLimit);
	rval *= 0.1;
	if (rval <= 4000) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumCurrentLimit_0x80030005(can_csm_secc_t *o, float64 in) {
	o->EvDcChargingVariable.EVMaximumCurrentLimit = 0;
	if (in > 4000)
		return -1;
	in *= 10;
	o->EvDcChargingVariable.EVMaximumCurrentLimit = in;
	return 0;
}

int candb_decode_csm_secc_EVMaximumVoltageLimit_0x80030005(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcChargingVariable.EVMaximumVoltageLimit);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumVoltageLimit_0x80030005(can_csm_secc_t *o, float64 in) {
	o->EvDcChargingVariable.EVMaximumVoltageLimit = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvDcChargingVariable.EVMaximumVoltageLimit = in;
	return 0;
}

static int pack_csm_secc_EvDcChargeParameter_0x80030006(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVEnergyCapacity: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->EvDcChargeParameter.EVEnergyCapacity)) & 0xffff;
	i |= x;
	/* EVEnergyRequest: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->EvDcChargeParameter.EVEnergyRequest)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMaximumPowerLimit: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcChargeParameter.EVMaximumPowerLimit)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* FullSOC: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDcChargeParameter.FullSOC)) & 0xff;
	x <<= 48; 
	i |= x;
	/* BulkSOC: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDcChargeParameter.BulkSOC)) & 0xff;
	x <<= 56; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvDcChargeParameter_0x80030006(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVEnergyCapacity: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->EvDcChargeParameter.EVEnergyCapacity = x;
	/* EVEnergyRequest: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvDcChargeParameter.EVEnergyRequest = x;
	/* EVMaximumPowerLimit: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvDcChargeParameter.EVMaximumPowerLimit = x;
	/* FullSOC: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xff;
	o->EvDcChargeParameter.FullSOC = x;
	/* BulkSOC: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 56) & 0xff;
	o->EvDcChargeParameter.BulkSOC = x;
	return 0;
}

int candb_decode_csm_secc_EVEnergyCapacity_0x80030006(const can_csm_secc_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->EvDcChargeParameter.EVEnergyCapacity);
	if (rval <= 2000) {
		*out = rval;
		return 0;
	} else {
		*out = (uint16)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVEnergyCapacity_0x80030006(can_csm_secc_t *o, uint16 in) {
	o->EvDcChargeParameter.EVEnergyCapacity = 0;
	if (in > 2000)
		return -1;
	o->EvDcChargeParameter.EVEnergyCapacity = in;
	return 0;
}

int candb_decode_csm_secc_EVEnergyRequest_0x80030006(const can_csm_secc_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->EvDcChargeParameter.EVEnergyRequest);
	if (rval <= 2000) {
		*out = rval;
		return 0;
	} else {
		*out = (uint16)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVEnergyRequest_0x80030006(can_csm_secc_t *o, uint16 in) {
	o->EvDcChargeParameter.EVEnergyRequest = 0;
	if (in > 2000)
		return -1;
	o->EvDcChargeParameter.EVEnergyRequest = in;
	return 0;
}

int candb_decode_csm_secc_EVMaximumPowerLimit_0x80030006(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcChargeParameter.EVMaximumPowerLimit);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumPowerLimit_0x80030006(can_csm_secc_t *o, float64 in) {
	o->EvDcChargeParameter.EVMaximumPowerLimit = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvDcChargeParameter.EVMaximumPowerLimit = in;
	return 0;
}

int candb_decode_csm_secc_FullSOC_0x80030006(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDcChargeParameter.FullSOC);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_FullSOC_0x80030006(can_csm_secc_t *o, uint8 in) {
	o->EvDcChargeParameter.FullSOC = in;
	return 0;
}

int candb_decode_csm_secc_BulkSOC_0x80030006(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDcChargeParameter.BulkSOC);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_BulkSOC_0x80030006(can_csm_secc_t *o, uint8 in) {
	o->EvDcChargeParameter.BulkSOC = in;
	return 0;
}

static int pack_csm_secc_EvDcMinimumChargeParam_0x80030007(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVMinimumPowerLimit: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcMinimumChargeParam.EVMinimumPowerLimit)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMinimumCurrentLimit: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcMinimumChargeParam.EVMinimumCurrentLimit)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* EVMinimumVoltageLimit: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcMinimumChargeParam.EVMinimumVoltageLimit)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvDcMinimumChargeParam_0x80030007(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVMinimumPowerLimit: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvDcMinimumChargeParam.EVMinimumPowerLimit = x;
	/* EVMinimumCurrentLimit: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvDcMinimumChargeParam.EVMinimumCurrentLimit = x;
	/* EVMinimumVoltageLimit: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->EvDcMinimumChargeParam.EVMinimumVoltageLimit = x;
	return 0;
}

int candb_decode_csm_secc_EVMinimumPowerLimit_0x80030007(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcMinimumChargeParam.EVMinimumPowerLimit);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumPowerLimit_0x80030007(can_csm_secc_t *o, float64 in) {
	o->EvDcMinimumChargeParam.EVMinimumPowerLimit = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvDcMinimumChargeParam.EVMinimumPowerLimit = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumCurrentLimit_0x80030007(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcMinimumChargeParam.EVMinimumCurrentLimit);
	rval *= 0.1;
	if (rval <= 4000) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumCurrentLimit_0x80030007(can_csm_secc_t *o, float64 in) {
	o->EvDcMinimumChargeParam.EVMinimumCurrentLimit = 0;
	if (in > 4000)
		return -1;
	in *= 10;
	o->EvDcMinimumChargeParam.EVMinimumCurrentLimit = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumVoltageLimit_0x80030007(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcMinimumChargeParam.EVMinimumVoltageLimit);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumVoltageLimit_0x80030007(can_csm_secc_t *o, float64 in) {
	o->EvDcMinimumChargeParam.EVMinimumVoltageLimit = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvDcMinimumChargeParam.EVMinimumVoltageLimit = in;
	return 0;
}

static int pack_csm_secc_EvDcDischargeParam_0x80030008(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVMaximumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcDischargeParam.EVMaximumDischargePower)) & 0xffff;
	i |= x;
	/* EVMinimumDischargePower: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcDischargeParam.EVMinimumDischargePower)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMaximumDischargeCurrent: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcDischargeParam.EVMaximumDischargeCurrent)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* EVMinimumDischargeCurrent: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvDcDischargeParam.EVMinimumDischargeCurrent)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvDcDischargeParam_0x80030008(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVMaximumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvDcDischargeParam.EVMaximumDischargePower = x;
	/* EVMinimumDischargePower: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvDcDischargeParam.EVMinimumDischargePower = x;
	/* EVMaximumDischargeCurrent: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvDcDischargeParam.EVMaximumDischargeCurrent = x;
	/* EVMinimumDischargeCurrent: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->EvDcDischargeParam.EVMinimumDischargeCurrent = x;
	return 0;
}

int candb_decode_csm_secc_EVMaximumDischargePower_0x80030008(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcDischargeParam.EVMaximumDischargePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumDischargePower_0x80030008(can_csm_secc_t *o, float64 in) {
	o->EvDcDischargeParam.EVMaximumDischargePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvDcDischargeParam.EVMaximumDischargePower = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumDischargePower_0x80030008(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcDischargeParam.EVMinimumDischargePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumDischargePower_0x80030008(can_csm_secc_t *o, float64 in) {
	o->EvDcDischargeParam.EVMinimumDischargePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvDcDischargeParam.EVMinimumDischargePower = in;
	return 0;
}

int candb_decode_csm_secc_EVMaximumDischargeCurrent_0x80030008(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcDischargeParam.EVMaximumDischargeCurrent);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumDischargeCurrent_0x80030008(can_csm_secc_t *o, float64 in) {
	o->EvDcDischargeParam.EVMaximumDischargeCurrent = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvDcDischargeParam.EVMaximumDischargeCurrent = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumDischargeCurrent_0x80030008(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvDcDischargeParam.EVMinimumDischargeCurrent);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumDischargeCurrent_0x80030008(can_csm_secc_t *o, float64 in) {
	o->EvDcDischargeParam.EVMinimumDischargeCurrent = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvDcDischargeParam.EVMinimumDischargeCurrent = in;
	return 0;
}

static int pack_csm_secc_EvAcChargeParam_0x80030009(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EAmount: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->EvAcChargeParam.EAmount)) & 0xffff;
	i |= x;
	/* EVMaxVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcChargeParam.EVMaxVoltage)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMaxCurrent: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcChargeParam.EVMaxCurrent)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* EVMinCurrent: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcChargeParam.EVMinCurrent)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvAcChargeParam_0x80030009(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EAmount: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->EvAcChargeParam.EAmount = x;
	/* EVMaxVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvAcChargeParam.EVMaxVoltage = x;
	/* EVMaxCurrent: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvAcChargeParam.EVMaxCurrent = x;
	/* EVMinCurrent: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->EvAcChargeParam.EVMinCurrent = x;
	return 0;
}

int candb_decode_csm_secc_EAmount_0x80030009(const can_csm_secc_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->EvAcChargeParam.EAmount);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_EAmount_0x80030009(can_csm_secc_t *o, uint16 in) {
	o->EvAcChargeParam.EAmount = in;
	return 0;
}

int candb_decode_csm_secc_EVMaxVoltage_0x80030009(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcChargeParam.EVMaxVoltage);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaxVoltage_0x80030009(can_csm_secc_t *o, float64 in) {
	o->EvAcChargeParam.EVMaxVoltage = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvAcChargeParam.EVMaxVoltage = in;
	return 0;
}

int candb_decode_csm_secc_EVMaxCurrent_0x80030009(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcChargeParam.EVMaxCurrent);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaxCurrent_0x80030009(can_csm_secc_t *o, float64 in) {
	o->EvAcChargeParam.EVMaxCurrent = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvAcChargeParam.EVMaxCurrent = in;
	return 0;
}

int candb_decode_csm_secc_EVMinCurrent_0x80030009(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcChargeParam.EVMinCurrent);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinCurrent_0x80030009(can_csm_secc_t *o, float64 in) {
	o->EvAcChargeParam.EVMinCurrent = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvAcChargeParam.EVMinCurrent = in;
	return 0;
}

static int pack_csm_secc_EvAcPresentActivePower_0x8003000a(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVPresentActivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcPresentActivePower.EVPresentActivePower)) & 0xffff;
	i |= x;
	/* EVPresentActivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcPresentActivePower.EVPresentActivePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVPresentActivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcPresentActivePower.EVPresentActivePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvAcPresentActivePower_0x8003000a(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVPresentActivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvAcPresentActivePower.EVPresentActivePower = x;
	/* EVPresentActivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvAcPresentActivePower.EVPresentActivePower_L2 = x;
	/* EVPresentActivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvAcPresentActivePower.EVPresentActivePower_L3 = x;
	return 0;
}

int candb_decode_csm_secc_EVPresentActivePower_0x8003000a(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcPresentActivePower.EVPresentActivePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVPresentActivePower_0x8003000a(can_csm_secc_t *o, float64 in) {
	o->EvAcPresentActivePower.EVPresentActivePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcPresentActivePower.EVPresentActivePower = in;
	return 0;
}

int candb_decode_csm_secc_EVPresentActivePower_L2_0x8003000a(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcPresentActivePower.EVPresentActivePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVPresentActivePower_L2_0x8003000a(can_csm_secc_t *o, float64 in) {
	o->EvAcPresentActivePower.EVPresentActivePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcPresentActivePower.EVPresentActivePower_L2 = in;
	return 0;
}

int candb_decode_csm_secc_EVPresentActivePower_L3_0x8003000a(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcPresentActivePower.EVPresentActivePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVPresentActivePower_L3_0x8003000a(can_csm_secc_t *o, float64 in) {
	o->EvAcPresentActivePower.EVPresentActivePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcPresentActivePower.EVPresentActivePower_L3 = in;
	return 0;
}

static int pack_csm_secc_EvAcPresentReactivePower_0x8003000b(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVPresentReactivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcPresentReactivePower.EVPresentReactivePower)) & 0xffff;
	i |= x;
	/* EVPresentReactivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcPresentReactivePower.EVPresentReactivePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVPresentReactivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcPresentReactivePower.EVPresentReactivePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvAcPresentReactivePower_0x8003000b(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVPresentReactivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvAcPresentReactivePower.EVPresentReactivePower = x;
	/* EVPresentReactivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvAcPresentReactivePower.EVPresentReactivePower_L2 = x;
	/* EVPresentReactivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvAcPresentReactivePower.EVPresentReactivePower_L3 = x;
	return 0;
}

int candb_decode_csm_secc_EVPresentReactivePower_0x8003000b(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcPresentReactivePower.EVPresentReactivePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVPresentReactivePower_0x8003000b(can_csm_secc_t *o, float64 in) {
	o->EvAcPresentReactivePower.EVPresentReactivePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcPresentReactivePower.EVPresentReactivePower = in;
	return 0;
}

int candb_decode_csm_secc_EVPresentReactivePower_L2_0x8003000b(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcPresentReactivePower.EVPresentReactivePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVPresentReactivePower_L2_0x8003000b(can_csm_secc_t *o, float64 in) {
	o->EvAcPresentReactivePower.EVPresentReactivePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcPresentReactivePower.EVPresentReactivePower_L2 = in;
	return 0;
}

int candb_decode_csm_secc_EVPresentReactivePower_L3_0x8003000b(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcPresentReactivePower.EVPresentReactivePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVPresentReactivePower_L3_0x8003000b(can_csm_secc_t *o, float64 in) {
	o->EvAcPresentReactivePower.EVPresentReactivePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcPresentReactivePower.EVPresentReactivePower_L3 = in;
	return 0;
}

static int pack_csm_secc_EvAcMaximumChargePower_0x8003000c(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVMaximumChargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMaximumChargePower.EVMaximumChargePower)) & 0xffff;
	i |= x;
	/* EVMaximumChargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMaximumChargePower.EVMaximumChargePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMaximumChargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMaximumChargePower.EVMaximumChargePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvAcMaximumChargePower_0x8003000c(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVMaximumChargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvAcMaximumChargePower.EVMaximumChargePower = x;
	/* EVMaximumChargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvAcMaximumChargePower.EVMaximumChargePower_L2 = x;
	/* EVMaximumChargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvAcMaximumChargePower.EVMaximumChargePower_L3 = x;
	return 0;
}

int candb_decode_csm_secc_EVMaximumChargePower_0x8003000c(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMaximumChargePower.EVMaximumChargePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumChargePower_0x8003000c(can_csm_secc_t *o, float64 in) {
	o->EvAcMaximumChargePower.EVMaximumChargePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcMaximumChargePower.EVMaximumChargePower = in;
	return 0;
}

int candb_decode_csm_secc_EVMaximumChargePower_L2_0x8003000c(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMaximumChargePower.EVMaximumChargePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumChargePower_L2_0x8003000c(can_csm_secc_t *o, float64 in) {
	o->EvAcMaximumChargePower.EVMaximumChargePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcMaximumChargePower.EVMaximumChargePower_L2 = in;
	return 0;
}

int candb_decode_csm_secc_EVMaximumChargePower_L3_0x8003000c(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMaximumChargePower.EVMaximumChargePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumChargePower_L3_0x8003000c(can_csm_secc_t *o, float64 in) {
	o->EvAcMaximumChargePower.EVMaximumChargePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcMaximumChargePower.EVMaximumChargePower_L3 = in;
	return 0;
}

static int pack_csm_secc_EvAcMinimumChargePower_0x8003000d(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVMinimumChargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMinimumChargePower.EVMinimumChargePower)) & 0xffff;
	i |= x;
	/* EVMinimumChargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMinimumChargePower.EVMinimumChargePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMinimumChargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMinimumChargePower.EVMinimumChargePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvAcMinimumChargePower_0x8003000d(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVMinimumChargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvAcMinimumChargePower.EVMinimumChargePower = x;
	/* EVMinimumChargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvAcMinimumChargePower.EVMinimumChargePower_L2 = x;
	/* EVMinimumChargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvAcMinimumChargePower.EVMinimumChargePower_L3 = x;
	return 0;
}

int candb_decode_csm_secc_EVMinimumChargePower_0x8003000d(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMinimumChargePower.EVMinimumChargePower);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumChargePower_0x8003000d(can_csm_secc_t *o, float64 in) {
	o->EvAcMinimumChargePower.EVMinimumChargePower = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvAcMinimumChargePower.EVMinimumChargePower = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumChargePower_L2_0x8003000d(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMinimumChargePower.EVMinimumChargePower_L2);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumChargePower_L2_0x8003000d(can_csm_secc_t *o, float64 in) {
	o->EvAcMinimumChargePower.EVMinimumChargePower_L2 = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvAcMinimumChargePower.EVMinimumChargePower_L2 = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumChargePower_L3_0x8003000d(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMinimumChargePower.EVMinimumChargePower_L3);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumChargePower_L3_0x8003000d(can_csm_secc_t *o, float64 in) {
	o->EvAcMinimumChargePower.EVMinimumChargePower_L3 = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvAcMinimumChargePower.EVMinimumChargePower_L3 = in;
	return 0;
}

static int pack_csm_secc_EvAcMaximumDischargePower_0x8003000e(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVMaximumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMaximumDischargePower.EVMaximumDischargePower)) & 0xffff;
	i |= x;
	/* EVMaximumDischargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMaximumDischargePower.EVMaximumDischargePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMaximumDischargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMaximumDischargePower.EVMaximumDischargePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvAcMaximumDischargePower_0x8003000e(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVMaximumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvAcMaximumDischargePower.EVMaximumDischargePower = x;
	/* EVMaximumDischargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvAcMaximumDischargePower.EVMaximumDischargePower_L2 = x;
	/* EVMaximumDischargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvAcMaximumDischargePower.EVMaximumDischargePower_L3 = x;
	return 0;
}

int candb_decode_csm_secc_EVMaximumDischargePower_0x8003000e(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMaximumDischargePower.EVMaximumDischargePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumDischargePower_0x8003000e(can_csm_secc_t *o, float64 in) {
	o->EvAcMaximumDischargePower.EVMaximumDischargePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcMaximumDischargePower.EVMaximumDischargePower = in;
	return 0;
}

int candb_decode_csm_secc_EVMaximumDischargePower_L2_0x8003000e(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMaximumDischargePower.EVMaximumDischargePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumDischargePower_L2_0x8003000e(can_csm_secc_t *o, float64 in) {
	o->EvAcMaximumDischargePower.EVMaximumDischargePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcMaximumDischargePower.EVMaximumDischargePower_L2 = in;
	return 0;
}

int candb_decode_csm_secc_EVMaximumDischargePower_L3_0x8003000e(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMaximumDischargePower.EVMaximumDischargePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumDischargePower_L3_0x8003000e(can_csm_secc_t *o, float64 in) {
	o->EvAcMaximumDischargePower.EVMaximumDischargePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcMaximumDischargePower.EVMaximumDischargePower_L3 = in;
	return 0;
}

static int pack_csm_secc_EvAcMinimumDischargePower_0x8003000f(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVMinimumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMinimumDischargePower.EVMinimumDischargePower)) & 0xffff;
	i |= x;
	/* EVMinimumDischargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMinimumDischargePower.EVMinimumDischargePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMinimumDischargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvAcMinimumDischargePower.EVMinimumDischargePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvAcMinimumDischargePower_0x8003000f(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVMinimumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvAcMinimumDischargePower.EVMinimumDischargePower = x;
	/* EVMinimumDischargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvAcMinimumDischargePower.EVMinimumDischargePower_L2 = x;
	/* EVMinimumDischargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvAcMinimumDischargePower.EVMinimumDischargePower_L3 = x;
	return 0;
}

int candb_decode_csm_secc_EVMinimumDischargePower_0x8003000f(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMinimumDischargePower.EVMinimumDischargePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumDischargePower_0x8003000f(can_csm_secc_t *o, float64 in) {
	o->EvAcMinimumDischargePower.EVMinimumDischargePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcMinimumDischargePower.EVMinimumDischargePower = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumDischargePower_L2_0x8003000f(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMinimumDischargePower.EVMinimumDischargePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumDischargePower_L2_0x8003000f(can_csm_secc_t *o, float64 in) {
	o->EvAcMinimumDischargePower.EVMinimumDischargePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcMinimumDischargePower.EVMinimumDischargePower_L2 = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumDischargePower_L3_0x8003000f(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvAcMinimumDischargePower.EVMinimumDischargePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumDischargePower_L3_0x8003000f(can_csm_secc_t *o, float64 in) {
	o->EvAcMinimumDischargePower.EVMinimumDischargePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvAcMinimumDischargePower.EVMinimumDischargePower_L3 = in;
	return 0;
}

static int pack_csm_secc_EvTargetEnergy_0x80030010(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVTargetEnergyRequest: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvTargetEnergy.EVTargetEnergyRequest)) & 0xffff;
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvTargetEnergy_0x80030010(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVTargetEnergyRequest: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvTargetEnergy.EVTargetEnergyRequest = x;
	return 0;
}

int candb_decode_csm_secc_EVTargetEnergyRequest_0x80030010(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvTargetEnergy.EVTargetEnergyRequest);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVTargetEnergyRequest_0x80030010(can_csm_secc_t *o, float64 in) {
	o->EvTargetEnergy.EVTargetEnergyRequest = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvTargetEnergy.EVTargetEnergyRequest = in;
	return 0;
}

static int pack_csm_secc_EvEnergyRequestLimit_0x80030011(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVMaximumEnergyRequest: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvEnergyRequestLimit.EVMaximumEnergyRequest)) & 0xffff;
	i |= x;
	/* EVMinimumEnergyRequest: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvEnergyRequestLimit.EVMinimumEnergyRequest)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVMaximumV2XEnergyRequest: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvEnergyRequestLimit.EVMaximumV2XEnergyRequest)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* EVMinimumV2XEnergyRequest: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->EvEnergyRequestLimit.EVMinimumV2XEnergyRequest)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvEnergyRequestLimit_0x80030011(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVMaximumEnergyRequest: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->EvEnergyRequestLimit.EVMaximumEnergyRequest = x;
	/* EVMinimumEnergyRequest: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->EvEnergyRequestLimit.EVMinimumEnergyRequest = x;
	/* EVMaximumV2XEnergyRequest: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->EvEnergyRequestLimit.EVMaximumV2XEnergyRequest = x;
	/* EVMinimumV2XEnergyRequest: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->EvEnergyRequestLimit.EVMinimumV2XEnergyRequest = x;
	return 0;
}

int candb_decode_csm_secc_EVMaximumEnergyRequest_0x80030011(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvEnergyRequestLimit.EVMaximumEnergyRequest);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumEnergyRequest_0x80030011(can_csm_secc_t *o, float64 in) {
	o->EvEnergyRequestLimit.EVMaximumEnergyRequest = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvEnergyRequestLimit.EVMaximumEnergyRequest = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumEnergyRequest_0x80030011(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvEnergyRequestLimit.EVMinimumEnergyRequest);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumEnergyRequest_0x80030011(can_csm_secc_t *o, float64 in) {
	o->EvEnergyRequestLimit.EVMinimumEnergyRequest = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->EvEnergyRequestLimit.EVMinimumEnergyRequest = in;
	return 0;
}

int candb_decode_csm_secc_EVMaximumV2XEnergyRequest_0x80030011(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvEnergyRequestLimit.EVMaximumV2XEnergyRequest);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMaximumV2XEnergyRequest_0x80030011(can_csm_secc_t *o, float64 in) {
	o->EvEnergyRequestLimit.EVMaximumV2XEnergyRequest = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvEnergyRequestLimit.EVMaximumV2XEnergyRequest = in;
	return 0;
}

int candb_decode_csm_secc_EVMinimumV2XEnergyRequest_0x80030011(const can_csm_secc_t *o, float64 *out) {
	float64 rval = (float64)(o->EvEnergyRequestLimit.EVMinimumV2XEnergyRequest);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_secc_EVMinimumV2XEnergyRequest_0x80030011(can_csm_secc_t *o, float64 in) {
	o->EvEnergyRequestLimit.EVMinimumV2XEnergyRequest = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->EvEnergyRequestLimit.EVMinimumV2XEnergyRequest = in;
	return 0;
}

static int pack_csm_secc_EvDisplayPresentStatus_0x8003001a(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* BatteryEnergyCapacity: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->EvDisplayPresentStatus.BatteryEnergyCapacity)) & 0xffff;
	x <<= 48; 
	i |= x;
	/* PresentSoc: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDisplayPresentStatus.PresentSoc)) & 0xff;
	i |= x;
	/* ChargingComplete: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDisplayPresentStatus.ChargingComplete)) & 0x1;
	x <<= 8; 
	i |= x;
	/* InletHot: start-bit 9, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDisplayPresentStatus.InletHot)) & 0x1;
	x <<= 9; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvDisplayPresentStatus_0x8003001a(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* BatteryEnergyCapacity: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->EvDisplayPresentStatus.BatteryEnergyCapacity = x;
	/* PresentSoc: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->EvDisplayPresentStatus.PresentSoc = x;
	/* ChargingComplete: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0x1;
	o->EvDisplayPresentStatus.ChargingComplete = x;
	/* InletHot: start-bit 9, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 9) & 0x1;
	o->EvDisplayPresentStatus.InletHot = x;
	return 0;
}

int candb_decode_csm_secc_BatteryEnergyCapacity_0x8003001a(const can_csm_secc_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->EvDisplayPresentStatus.BatteryEnergyCapacity);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_BatteryEnergyCapacity_0x8003001a(can_csm_secc_t *o, uint16 in) {
	o->EvDisplayPresentStatus.BatteryEnergyCapacity = in;
	return 0;
}

int candb_decode_csm_secc_PresentSoc_0x8003001a(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDisplayPresentStatus.PresentSoc);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_PresentSoc_0x8003001a(can_csm_secc_t *o, uint8 in) {
	o->EvDisplayPresentStatus.PresentSoc = in;
	return 0;
}

int candb_decode_csm_secc_ChargingComplete_0x8003001a(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDisplayPresentStatus.ChargingComplete);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_ChargingComplete_0x8003001a(can_csm_secc_t *o, uint8 in) {
	o->EvDisplayPresentStatus.ChargingComplete = in;
	return 0;
}

int candb_decode_csm_secc_InletHot_0x8003001a(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDisplayPresentStatus.InletHot);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_InletHot_0x8003001a(can_csm_secc_t *o, uint8 in) {
	o->EvDisplayPresentStatus.InletHot = in;
	return 0;
}

static int pack_csm_secc_EvDisplayTargetSoc_0x8003001b(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* RemainingTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32)(o->EvDisplayTargetSoc.RemainingTime)) & 0xffffffff;
	x <<= 32; 
	i |= x;
	/* TargetSoc: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDisplayTargetSoc.TargetSoc)) & 0xff;
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvDisplayTargetSoc_0x8003001b(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* RemainingTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->EvDisplayTargetSoc.RemainingTime = x;
	/* TargetSoc: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->EvDisplayTargetSoc.TargetSoc = x;
	return 0;
}

int candb_decode_csm_secc_RemainingTime_0x8003001b(const can_csm_secc_t *o, uint32 *out) {
	uint32 rval = (uint32)(o->EvDisplayTargetSoc.RemainingTime);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_RemainingTime_0x8003001b(can_csm_secc_t *o, uint32 in) {
	o->EvDisplayTargetSoc.RemainingTime = in;
	return 0;
}

int candb_decode_csm_secc_TargetSoc_0x8003001b(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDisplayTargetSoc.TargetSoc);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_TargetSoc_0x8003001b(can_csm_secc_t *o, uint8 in) {
	o->EvDisplayTargetSoc.TargetSoc = in;
	return 0;
}

static int pack_csm_secc_EvDisplayMaximumSoc_0x8003001c(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* RemainingTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32)(o->EvDisplayMaximumSoc.RemainingTime)) & 0xffffffff;
	x <<= 32; 
	i |= x;
	/* MaximumSoc: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDisplayMaximumSoc.MaximumSoc)) & 0xff;
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvDisplayMaximumSoc_0x8003001c(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* RemainingTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->EvDisplayMaximumSoc.RemainingTime = x;
	/* MaximumSoc: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->EvDisplayMaximumSoc.MaximumSoc = x;
	return 0;
}

int candb_decode_csm_secc_RemainingTime_0x8003001c(const can_csm_secc_t *o, uint32 *out) {
	uint32 rval = (uint32)(o->EvDisplayMaximumSoc.RemainingTime);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_RemainingTime_0x8003001c(can_csm_secc_t *o, uint32 in) {
	o->EvDisplayMaximumSoc.RemainingTime = in;
	return 0;
}

int candb_decode_csm_secc_MaximumSoc_0x8003001c(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDisplayMaximumSoc.MaximumSoc);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_MaximumSoc_0x8003001c(can_csm_secc_t *o, uint8 in) {
	o->EvDisplayMaximumSoc.MaximumSoc = in;
	return 0;
}

static int pack_csm_secc_EvDisplayMinimumSoc_0x8003001d(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* RemainingTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = ((uint32)(o->EvDisplayMinimumSoc.RemainingTime)) & 0xffffffff;
	x <<= 32; 
	i |= x;
	/* MinimumSoc: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->EvDisplayMinimumSoc.MinimumSoc)) & 0xff;
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_EvDisplayMinimumSoc_0x8003001d(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* RemainingTime: start-bit 32, length 32, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->EvDisplayMinimumSoc.RemainingTime = x;
	/* MinimumSoc: start-bit 0, length 8, endianess intel, scaling 1, offset 0 */
	x = i & 0xff;
	o->EvDisplayMinimumSoc.MinimumSoc = x;
	return 0;
}

int candb_decode_csm_secc_RemainingTime_0x8003001d(const can_csm_secc_t *o, uint32 *out) {
	uint32 rval = (uint32)(o->EvDisplayMinimumSoc.RemainingTime);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_RemainingTime_0x8003001d(can_csm_secc_t *o, uint32 in) {
	o->EvDisplayMinimumSoc.RemainingTime = in;
	return 0;
}

int candb_decode_csm_secc_MinimumSoc_0x8003001d(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->EvDisplayMinimumSoc.MinimumSoc);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_MinimumSoc_0x8003001d(can_csm_secc_t *o, uint8 in) {
	o->EvDisplayMinimumSoc.MinimumSoc = in;
	return 0;
}

static int pack_csm_secc_KVasEvBatteryHeader_0x80030101(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* VasDataLength: start-bit 40, length 10, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->KVasEvBatteryHeader.VasDataLength)) & 0x3ff;
	x <<= 40; 
	i |= x;
	/* VasReceivedCount: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryHeader.VasReceivedCount)) & 0xff;
	x <<= 32; 
	i |= x;
	/* VasDataChecksum: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryHeader.VasDataChecksum)) & 0xff;
	x <<= 56; 
	i |= x;
	/* VasState: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryHeader.VasState)) & 0xf;
	x <<= 8; 
	i |= x;
	/* VasErrorCode: start-bit 12, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryHeader.VasErrorCode)) & 0xf;
	x <<= 12; 
	i |= x;
	/* VasEnabled: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryHeader.VasEnabled)) & 0x1;
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_KVasEvBatteryHeader_0x80030101(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* VasDataLength: start-bit 40, length 10, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0x3ff;
	o->KVasEvBatteryHeader.VasDataLength = x;
	/* VasReceivedCount: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xff;
	o->KVasEvBatteryHeader.VasReceivedCount = x;
	/* VasDataChecksum: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 56) & 0xff;
	o->KVasEvBatteryHeader.VasDataChecksum = x;
	/* VasState: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xf;
	o->KVasEvBatteryHeader.VasState = x;
	/* VasErrorCode: start-bit 12, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 12) & 0xf;
	o->KVasEvBatteryHeader.VasErrorCode = x;
	/* VasEnabled: start-bit 0, length 1, endianess intel, scaling 1, offset 0 */
	x = i & 0x1;
	o->KVasEvBatteryHeader.VasEnabled = x;
	return 0;
}

int candb_decode_csm_secc_VasDataLength_0x80030101(const can_csm_secc_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->KVasEvBatteryHeader.VasDataLength);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_VasDataLength_0x80030101(can_csm_secc_t *o, uint16 in) {
	o->KVasEvBatteryHeader.VasDataLength = in;
	return 0;
}

int candb_decode_csm_secc_VasReceivedCount_0x80030101(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryHeader.VasReceivedCount);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_VasReceivedCount_0x80030101(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryHeader.VasReceivedCount = in;
	return 0;
}

int candb_decode_csm_secc_VasDataChecksum_0x80030101(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryHeader.VasDataChecksum);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_VasDataChecksum_0x80030101(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryHeader.VasDataChecksum = in;
	return 0;
}

int candb_decode_csm_secc_VasState_0x80030101(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryHeader.VasState);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_VasState_0x80030101(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryHeader.VasState = in;
	return 0;
}

int candb_decode_csm_secc_VasErrorCode_0x80030101(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryHeader.VasErrorCode);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_VasErrorCode_0x80030101(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryHeader.VasErrorCode = in;
	return 0;
}

int candb_decode_csm_secc_VasEnabled_0x80030101(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryHeader.VasEnabled);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_VasEnabled_0x80030101(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryHeader.VasEnabled = in;
	return 0;
}

static int pack_csm_secc_KVasEvBatteryData_0x80030102(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* Data0_or_Length: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryData.Data0_or_Length)) & 0xff;
	x <<= 8; 
	i |= x;
	/* Data1: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryData.Data1)) & 0xff;
	x <<= 16; 
	i |= x;
	/* Data2: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryData.Data2)) & 0xff;
	x <<= 24; 
	i |= x;
	/* Data3: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryData.Data3)) & 0xff;
	x <<= 32; 
	i |= x;
	/* Data4: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryData.Data4)) & 0xff;
	x <<= 40; 
	i |= x;
	/* Data5: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryData.Data5)) & 0xff;
	x <<= 48; 
	i |= x;
	/* Data6: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryData.Data6)) & 0xff;
	x <<= 56; 
	i |= x;
	/* SN_or_Length: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryData.SN_or_Length)) & 0xf;
	i |= x;
	/* FrameType: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->KVasEvBatteryData.FrameType)) & 0xf;
	x <<= 4; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_KVasEvBatteryData_0x80030102(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* Data0_or_Length: start-bit 8, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xff;
	o->KVasEvBatteryData.Data0_or_Length = x;
	/* Data1: start-bit 16, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xff;
	o->KVasEvBatteryData.Data1 = x;
	/* Data2: start-bit 24, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0xff;
	o->KVasEvBatteryData.Data2 = x;
	/* Data3: start-bit 32, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xff;
	o->KVasEvBatteryData.Data3 = x;
	/* Data4: start-bit 40, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xff;
	o->KVasEvBatteryData.Data4 = x;
	/* Data5: start-bit 48, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xff;
	o->KVasEvBatteryData.Data5 = x;
	/* Data6: start-bit 56, length 8, endianess intel, scaling 1, offset 0 */
	x = (i >> 56) & 0xff;
	o->KVasEvBatteryData.Data6 = x;
	/* SN_or_Length: start-bit 0, length 4, endianess intel, scaling 1, offset 0 */
	x = i & 0xf;
	o->KVasEvBatteryData.SN_or_Length = x;
	/* FrameType: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->KVasEvBatteryData.FrameType = x;
	return 0;
}

int candb_decode_csm_secc_Data0_or_Length_0x80030102(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryData.Data0_or_Length);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Data0_or_Length_0x80030102(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryData.Data0_or_Length = in;
	return 0;
}

int candb_decode_csm_secc_Data1_0x80030102(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryData.Data1);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Data1_0x80030102(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryData.Data1 = in;
	return 0;
}

int candb_decode_csm_secc_Data2_0x80030102(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryData.Data2);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Data2_0x80030102(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryData.Data2 = in;
	return 0;
}

int candb_decode_csm_secc_Data3_0x80030102(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryData.Data3);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Data3_0x80030102(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryData.Data3 = in;
	return 0;
}

int candb_decode_csm_secc_Data4_0x80030102(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryData.Data4);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Data4_0x80030102(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryData.Data4 = in;
	return 0;
}

int candb_decode_csm_secc_Data5_0x80030102(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryData.Data5);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Data5_0x80030102(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryData.Data5 = in;
	return 0;
}

int candb_decode_csm_secc_Data6_0x80030102(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryData.Data6);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Data6_0x80030102(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryData.Data6 = in;
	return 0;
}

int candb_decode_csm_secc_SN_or_Length_0x80030102(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryData.SN_or_Length);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_SN_or_Length_0x80030102(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryData.SN_or_Length = in;
	return 0;
}

int candb_decode_csm_secc_FrameType_0x80030102(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->KVasEvBatteryData.FrameType);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_FrameType_0x80030102(can_csm_secc_t *o, uint8 in) {
	o->KVasEvBatteryData.FrameType = in;
	return 0;
}

static int pack_csm_secc_SeccDateTime_0x800301f1(can_csm_secc_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* Year: start-bit 0, length 7, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccDateTime.Year)) & 0x7f;
	i |= x;
	/* Minutes: start-bit 32, length 6, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccDateTime.Minutes)) & 0x3f;
	x <<= 32; 
	i |= x;
	/* Seconds: start-bit 40, length 6, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccDateTime.Seconds)) & 0x3f;
	x <<= 40; 
	i |= x;
	/* Day: start-bit 16, length 5, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccDateTime.Day)) & 0x1f;
	x <<= 16; 
	i |= x;
	/* Hours: start-bit 24, length 5, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccDateTime.Hours)) & 0x1f;
	x <<= 24; 
	i |= x;
	/* Month: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->SeccDateTime.Month)) & 0xf;
	x <<= 8; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_secc_SeccDateTime_0x800301f1(can_csm_secc_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* Year: start-bit 0, length 7, endianess intel, scaling 1, offset 0 */
	x = i & 0x7f;
	o->SeccDateTime.Year = x;
	/* Minutes: start-bit 32, length 6, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0x3f;
	o->SeccDateTime.Minutes = x;
	/* Seconds: start-bit 40, length 6, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0x3f;
	o->SeccDateTime.Seconds = x;
	/* Day: start-bit 16, length 5, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0x1f;
	o->SeccDateTime.Day = x;
	/* Hours: start-bit 24, length 5, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0x1f;
	o->SeccDateTime.Hours = x;
	/* Month: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xf;
	o->SeccDateTime.Month = x;
	return 0;
}

int candb_decode_csm_secc_Year_0x800301f1(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccDateTime.Year);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Year_0x800301f1(can_csm_secc_t *o, uint8 in) {
	o->SeccDateTime.Year = in;
	return 0;
}

int candb_decode_csm_secc_Minutes_0x800301f1(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccDateTime.Minutes);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Minutes_0x800301f1(can_csm_secc_t *o, uint8 in) {
	o->SeccDateTime.Minutes = in;
	return 0;
}

int candb_decode_csm_secc_Seconds_0x800301f1(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccDateTime.Seconds);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Seconds_0x800301f1(can_csm_secc_t *o, uint8 in) {
	o->SeccDateTime.Seconds = in;
	return 0;
}

int candb_decode_csm_secc_Day_0x800301f1(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccDateTime.Day);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Day_0x800301f1(can_csm_secc_t *o, uint8 in) {
	o->SeccDateTime.Day = in;
	return 0;
}

int candb_decode_csm_secc_Hours_0x800301f1(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccDateTime.Hours);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Hours_0x800301f1(can_csm_secc_t *o, uint8 in) {
	o->SeccDateTime.Hours = in;
	return 0;
}

int candb_decode_csm_secc_Month_0x800301f1(const can_csm_secc_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->SeccDateTime.Month);
	*out = rval;
	return 0;
}

int candb_encode_csm_secc_Month_0x800301f1(can_csm_secc_t *o, uint8 in) {
	o->SeccDateTime.Month = in;
	return 0;
}

int candb_csm_secc_unpack_message(can_csm_secc_t *o, const unsigned long id, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	switch (id) {
	case 0x80030001: return unpack_csm_secc_SeccInformation_0x80030001(o, data, dlc, time_stamp);
	case 0x80030002: return unpack_csm_secc_EvEvccId_0x80030002(o, data, dlc, time_stamp);
	case 0x80030003: return unpack_csm_secc_EvChargingService_0x80030003(o, data, dlc, time_stamp);
	case 0x80030004: return unpack_csm_secc_EvDcChargingStatus_0x80030004(o, data, dlc, time_stamp);
	case 0x80030005: return unpack_csm_secc_EvDcChargingVariable_0x80030005(o, data, dlc, time_stamp);
	case 0x80030006: return unpack_csm_secc_EvDcChargeParameter_0x80030006(o, data, dlc, time_stamp);
	case 0x80030007: return unpack_csm_secc_EvDcMinimumChargeParam_0x80030007(o, data, dlc, time_stamp);
	case 0x80030008: return unpack_csm_secc_EvDcDischargeParam_0x80030008(o, data, dlc, time_stamp);
	case 0x80030009: return unpack_csm_secc_EvAcChargeParam_0x80030009(o, data, dlc, time_stamp);
	case 0x8003000a: return unpack_csm_secc_EvAcPresentActivePower_0x8003000a(o, data, dlc, time_stamp);
	case 0x8003000b: return unpack_csm_secc_EvAcPresentReactivePower_0x8003000b(o, data, dlc, time_stamp);
	case 0x8003000c: return unpack_csm_secc_EvAcMaximumChargePower_0x8003000c(o, data, dlc, time_stamp);
	case 0x8003000d: return unpack_csm_secc_EvAcMinimumChargePower_0x8003000d(o, data, dlc, time_stamp);
	case 0x8003000e: return unpack_csm_secc_EvAcMaximumDischargePower_0x8003000e(o, data, dlc, time_stamp);
	case 0x8003000f: return unpack_csm_secc_EvAcMinimumDischargePower_0x8003000f(o, data, dlc, time_stamp);
	case 0x80030010: return unpack_csm_secc_EvTargetEnergy_0x80030010(o, data, dlc, time_stamp);
	case 0x80030011: return unpack_csm_secc_EvEnergyRequestLimit_0x80030011(o, data, dlc, time_stamp);
	case 0x8003001a: return unpack_csm_secc_EvDisplayPresentStatus_0x8003001a(o, data, dlc, time_stamp);
	case 0x8003001b: return unpack_csm_secc_EvDisplayTargetSoc_0x8003001b(o, data, dlc, time_stamp);
	case 0x8003001c: return unpack_csm_secc_EvDisplayMaximumSoc_0x8003001c(o, data, dlc, time_stamp);
	case 0x8003001d: return unpack_csm_secc_EvDisplayMinimumSoc_0x8003001d(o, data, dlc, time_stamp);
	case 0x80030101: return unpack_csm_secc_KVasEvBatteryHeader_0x80030101(o, data, dlc, time_stamp);
	case 0x80030102: return unpack_csm_secc_KVasEvBatteryData_0x80030102(o, data, dlc, time_stamp);
	case 0x800301f1: return unpack_csm_secc_SeccDateTime_0x800301f1(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int candb_csm_secc_pack_message(can_csm_secc_t *o, const unsigned long id, uint64 *data) {
	switch (id) {
	case 0x80030001: return pack_csm_secc_SeccInformation_0x80030001(o, data);
	case 0x80030002: return pack_csm_secc_EvEvccId_0x80030002(o, data);
	case 0x80030003: return pack_csm_secc_EvChargingService_0x80030003(o, data);
	case 0x80030004: return pack_csm_secc_EvDcChargingStatus_0x80030004(o, data);
	case 0x80030005: return pack_csm_secc_EvDcChargingVariable_0x80030005(o, data);
	case 0x80030006: return pack_csm_secc_EvDcChargeParameter_0x80030006(o, data);
	case 0x80030007: return pack_csm_secc_EvDcMinimumChargeParam_0x80030007(o, data);
	case 0x80030008: return pack_csm_secc_EvDcDischargeParam_0x80030008(o, data);
	case 0x80030009: return pack_csm_secc_EvAcChargeParam_0x80030009(o, data);
	case 0x8003000a: return pack_csm_secc_EvAcPresentActivePower_0x8003000a(o, data);
	case 0x8003000b: return pack_csm_secc_EvAcPresentReactivePower_0x8003000b(o, data);
	case 0x8003000c: return pack_csm_secc_EvAcMaximumChargePower_0x8003000c(o, data);
	case 0x8003000d: return pack_csm_secc_EvAcMinimumChargePower_0x8003000d(o, data);
	case 0x8003000e: return pack_csm_secc_EvAcMaximumDischargePower_0x8003000e(o, data);
	case 0x8003000f: return pack_csm_secc_EvAcMinimumDischargePower_0x8003000f(o, data);
	case 0x80030010: return pack_csm_secc_EvTargetEnergy_0x80030010(o, data);
	case 0x80030011: return pack_csm_secc_EvEnergyRequestLimit_0x80030011(o, data);
	case 0x8003001a: return pack_csm_secc_EvDisplayPresentStatus_0x8003001a(o, data);
	case 0x8003001b: return pack_csm_secc_EvDisplayTargetSoc_0x8003001b(o, data);
	case 0x8003001c: return pack_csm_secc_EvDisplayMaximumSoc_0x8003001c(o, data);
	case 0x8003001d: return pack_csm_secc_EvDisplayMinimumSoc_0x8003001d(o, data);
	case 0x80030101: return pack_csm_secc_KVasEvBatteryHeader_0x80030101(o, data);
	case 0x80030102: return pack_csm_secc_KVasEvBatteryData_0x80030102(o, data);
	case 0x800301f1: return pack_csm_secc_SeccDateTime_0x800301f1(o, data);
	default: break; 
	}
	return -1; 
}

