/* Generated by DBCC, see <https://github.com/howerj/dbcc> */
#include "csm_charger.h"

#define UNUSED(X) ((void)(X))

static inline uint64 reverse_byte_order(uint64 x) {
	x = (x & 0x00000000FFFFFFFF) << 32 | (x & 0xFFFFFFFF00000000) >> 32;
	x = (x & 0x0000FFFF0000FFFF) << 16 | (x & 0xFFFF0000FFFF0000) >> 16;
	x = (x & 0x00FF00FF00FF00FF) << 8  | (x & 0xFF00FF00FF00FF00) >> 8;
	return x;
}

#define CANID_ChargerStatus_80040001h (0x80040001)
#define CANID_ChargerChargingVariable_80040002h (0x80040002)
#define CANID_ChargerChargingService_80040003h (0x80040003)
#define CANID_ChargerDcChargeParameter1_80040006h (0x80040006)
#define CANID_ChargerDcChargeParameter2_80040007h (0x80040007)
#define CANID_ChargerDcDischargeParam_80040008h (0x80040008)
#define CANID_ChargerAcChargeParam_80040009h (0x80040009)
#define CANID_ChargerAcPresentActivePower_8004000bh (0x8004000b)
#define CANID_ChargerAcTargetActivePower_8004000ch (0x8004000c)
#define CANID_ChargerAcTargetReactivePower_8004000dh (0x8004000d)
#define CANID_ChargerAcMaximumChargePower_8004000eh (0x8004000e)
#define CANID_ChargerAcMinimumChargePower_8004000fh (0x8004000f)
#define CANID_ChargerAcMaximumDischargePower_80040010h (0x80040010)
#define CANID_ChargerAcMinimumDischargePower_80040011h (0x80040011)
#define CANID_ChargerAcChargingSafety_80040012h (0x80040012)
#define CANID_ChargerAcFrtLvrt_80040020h (0x80040020)
#define CANID_ChargerAcFrtHvrt_80040021h (0x80040021)
#define CANID_ChargerAcFrtReactivePower_80040022h (0x80040022)
#define CANID_ChargerDateTime_800401f1h (0x800401f1)

const static int enum_to_id[] = {
  CANID_ChargerStatus_80040001h,
  CANID_ChargerChargingVariable_80040002h,
  CANID_ChargerChargingService_80040003h,
  CANID_ChargerDcChargeParameter1_80040006h,
  CANID_ChargerDcChargeParameter2_80040007h,
  CANID_ChargerDcDischargeParam_80040008h,
  CANID_ChargerAcChargeParam_80040009h,
  CANID_ChargerAcPresentActivePower_8004000bh,
  CANID_ChargerAcTargetActivePower_8004000ch,
  CANID_ChargerAcTargetReactivePower_8004000dh,
  CANID_ChargerAcMaximumChargePower_8004000eh,
  CANID_ChargerAcMinimumChargePower_8004000fh,
  CANID_ChargerAcMaximumDischargePower_80040010h,
  CANID_ChargerAcMinimumDischargePower_80040011h,
  CANID_ChargerAcChargingSafety_80040012h,
  CANID_ChargerAcFrtLvrt_80040020h,
  CANID_ChargerAcFrtHvrt_80040021h,
  CANID_ChargerAcFrtReactivePower_80040022h,
  CANID_ChargerDateTime_800401f1h,
};

int candb_csm_charger_get_can_id(csm_charger_msg_types msg_type) {
  return (msg_type < csm_charger_msg_max_count) ? enum_to_id[msg_type] : 0;
}

static int pack_csm_charger_ChargerStatus_0x80040001(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* ChargingEnergyTransferType: start-bit 40, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.ChargingEnergyTransferType)) & 0xf;
	x <<= 40; 
	i |= x;
	/* BptSupported: start-bit 44, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.BptSupported)) & 0x3;
	x <<= 44; 
	i |= x;
	/* ChargingPriority: start-bit 46, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.ChargingPriority)) & 0x3;
	x <<= 46; 
	i |= x;
	/* IdentificationOptionType: start-bit 48, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.IdentificationOptionType)) & 0x3;
	x <<= 48; 
	i |= x;
	/* Iso20ControlMode: start-bit 56, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.Iso20ControlMode)) & 0x3;
	x <<= 56; 
	i |= x;
	/* ChargingStatus: start-bit 1, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.ChargingStatus)) & 0x1;
	x <<= 1; 
	i |= x;
	/* ChargingStopControl: start-bit 2, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.ChargingStopControl)) & 0x1;
	x <<= 2; 
	i |= x;
	/* EVSEMalfunction: start-bit 3, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.EVSEMalfunction)) & 0x1;
	x <<= 3; 
	i |= x;
	/* EmergencyShutdown: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.EmergencyShutdown)) & 0x1;
	x <<= 4; 
	i |= x;
	/* AuthFinished: start-bit 5, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.AuthFinished)) & 0x1;
	x <<= 5; 
	i |= x;
	/* ChargeParameterFinished: start-bit 6, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.ChargeParameterFinished)) & 0x1;
	x <<= 6; 
	i |= x;
	/* DcCableIsolationChecked: start-bit 7, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.DcCableIsolationChecked)) & 0x1;
	x <<= 7; 
	i |= x;
	/* DcEVSECurrentLimitAchieved: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.DcEVSECurrentLimitAchieved)) & 0x1;
	x <<= 8; 
	i |= x;
	/* DcEVSEVoltageLimitAchieved: start-bit 9, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.DcEVSEVoltageLimitAchieved)) & 0x1;
	x <<= 9; 
	i |= x;
	/* DcEVSEPowerLimitAchieved: start-bit 10, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.DcEVSEPowerLimitAchieved)) & 0x1;
	x <<= 10; 
	i |= x;
	/* DcCableIsolationFaulted: start-bit 11, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.DcCableIsolationFaulted)) & 0x1;
	x <<= 11; 
	i |= x;
	/* ServiceRenegotiationSupported: start-bit 59, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.ServiceRenegotiationSupported)) & 0x1;
	x <<= 59; 
	i |= x;
	/* VasEnable: start-bit 63, length 1, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerStatus.VasEnable)) & 0x1;
	x <<= 63; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerStatus_0x80040001(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* ChargingEnergyTransferType: start-bit 40, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0xf;
	o->ChargerStatus.ChargingEnergyTransferType = x;
	/* BptSupported: start-bit 44, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 44) & 0x3;
	o->ChargerStatus.BptSupported = x;
	/* ChargingPriority: start-bit 46, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 46) & 0x3;
	o->ChargerStatus.ChargingPriority = x;
	/* IdentificationOptionType: start-bit 48, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0x3;
	o->ChargerStatus.IdentificationOptionType = x;
	/* Iso20ControlMode: start-bit 56, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 56) & 0x3;
	o->ChargerStatus.Iso20ControlMode = x;
	/* ChargingStatus: start-bit 1, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 1) & 0x1;
	o->ChargerStatus.ChargingStatus = x;
	/* ChargingStopControl: start-bit 2, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 2) & 0x1;
	o->ChargerStatus.ChargingStopControl = x;
	/* EVSEMalfunction: start-bit 3, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 3) & 0x1;
	o->ChargerStatus.EVSEMalfunction = x;
	/* EmergencyShutdown: start-bit 4, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0x1;
	o->ChargerStatus.EmergencyShutdown = x;
	/* AuthFinished: start-bit 5, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 5) & 0x1;
	o->ChargerStatus.AuthFinished = x;
	/* ChargeParameterFinished: start-bit 6, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 6) & 0x1;
	o->ChargerStatus.ChargeParameterFinished = x;
	/* DcCableIsolationChecked: start-bit 7, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 7) & 0x1;
	o->ChargerStatus.DcCableIsolationChecked = x;
	/* DcEVSECurrentLimitAchieved: start-bit 8, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0x1;
	o->ChargerStatus.DcEVSECurrentLimitAchieved = x;
	/* DcEVSEVoltageLimitAchieved: start-bit 9, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 9) & 0x1;
	o->ChargerStatus.DcEVSEVoltageLimitAchieved = x;
	/* DcEVSEPowerLimitAchieved: start-bit 10, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 10) & 0x1;
	o->ChargerStatus.DcEVSEPowerLimitAchieved = x;
	/* DcCableIsolationFaulted: start-bit 11, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 11) & 0x1;
	o->ChargerStatus.DcCableIsolationFaulted = x;
	/* ServiceRenegotiationSupported: start-bit 59, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 59) & 0x1;
	o->ChargerStatus.ServiceRenegotiationSupported = x;
	/* VasEnable: start-bit 63, length 1, endianess intel, scaling 1, offset 0 */
	x = (i >> 63) & 0x1;
	o->ChargerStatus.VasEnable = x;
	return 0;
}

int candb_decode_csm_charger_ChargingEnergyTransferType_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.ChargingEnergyTransferType);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_ChargingEnergyTransferType_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.ChargingEnergyTransferType = in;
	return 0;
}

int candb_decode_csm_charger_BptSupported_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.BptSupported);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_BptSupported_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.BptSupported = in;
	return 0;
}

int candb_decode_csm_charger_ChargingPriority_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.ChargingPriority);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_ChargingPriority_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.ChargingPriority = in;
	return 0;
}

int candb_decode_csm_charger_IdentificationOptionType_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.IdentificationOptionType);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_IdentificationOptionType_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.IdentificationOptionType = in;
	return 0;
}

int candb_decode_csm_charger_Iso20ControlMode_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.Iso20ControlMode);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_Iso20ControlMode_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.Iso20ControlMode = in;
	return 0;
}

int candb_decode_csm_charger_ChargingStatus_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.ChargingStatus);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_ChargingStatus_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.ChargingStatus = in;
	return 0;
}

int candb_decode_csm_charger_ChargingStopControl_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.ChargingStopControl);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_ChargingStopControl_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.ChargingStopControl = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMalfunction_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.EVSEMalfunction);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_EVSEMalfunction_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.EVSEMalfunction = in;
	return 0;
}

int candb_decode_csm_charger_EmergencyShutdown_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.EmergencyShutdown);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_EmergencyShutdown_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.EmergencyShutdown = in;
	return 0;
}

int candb_decode_csm_charger_AuthFinished_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.AuthFinished);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_AuthFinished_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.AuthFinished = in;
	return 0;
}

int candb_decode_csm_charger_ChargeParameterFinished_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.ChargeParameterFinished);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_ChargeParameterFinished_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.ChargeParameterFinished = in;
	return 0;
}

int candb_decode_csm_charger_DcCableIsolationChecked_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.DcCableIsolationChecked);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_DcCableIsolationChecked_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.DcCableIsolationChecked = in;
	return 0;
}

int candb_decode_csm_charger_DcEVSECurrentLimitAchieved_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.DcEVSECurrentLimitAchieved);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_DcEVSECurrentLimitAchieved_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.DcEVSECurrentLimitAchieved = in;
	return 0;
}

int candb_decode_csm_charger_DcEVSEVoltageLimitAchieved_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.DcEVSEVoltageLimitAchieved);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_DcEVSEVoltageLimitAchieved_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.DcEVSEVoltageLimitAchieved = in;
	return 0;
}

int candb_decode_csm_charger_DcEVSEPowerLimitAchieved_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.DcEVSEPowerLimitAchieved);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_DcEVSEPowerLimitAchieved_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.DcEVSEPowerLimitAchieved = in;
	return 0;
}

int candb_decode_csm_charger_DcCableIsolationFaulted_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.DcCableIsolationFaulted);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_DcCableIsolationFaulted_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.DcCableIsolationFaulted = in;
	return 0;
}

int candb_decode_csm_charger_ServiceRenegotiationSupported_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.ServiceRenegotiationSupported);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_ServiceRenegotiationSupported_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.ServiceRenegotiationSupported = in;
	return 0;
}

int candb_decode_csm_charger_VasEnable_0x80040001(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerStatus.VasEnable);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_VasEnable_0x80040001(can_csm_charger_t *o, uint8 in) {
	o->ChargerStatus.VasEnable = in;
	return 0;
}

static int pack_csm_charger_ChargerChargingVariable_0x80040002(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* MeteringValue: start-bit 32, length 32, endianess intel, scaling 0.01, offset 0 */
	x = ((uint32)(o->ChargerChargingVariable.MeteringValue)) & 0xffffffff;
	x <<= 32; 
	i |= x;
	/* EVSEPresentVoltage: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerChargingVariable.EVSEPresentVoltage)) & 0xffff;
	i |= x;
	/* EVSEPresentCurrent: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerChargingVariable.EVSEPresentCurrent)) & 0xffff;
	x <<= 16; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerChargingVariable_0x80040002(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* MeteringValue: start-bit 32, length 32, endianess intel, scaling 0.01, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->ChargerChargingVariable.MeteringValue = x;
	/* EVSEPresentVoltage: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerChargingVariable.EVSEPresentVoltage = x;
	/* EVSEPresentCurrent: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerChargingVariable.EVSEPresentCurrent = x;
	return 0;
}

int candb_decode_csm_charger_MeteringValue_0x80040002(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerChargingVariable.MeteringValue);
	rval *= 0.01;
	if (rval <= 4.29497e+07) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_MeteringValue_0x80040002(can_csm_charger_t *o, float64 in) {
	o->ChargerChargingVariable.MeteringValue = 0;
	if (in > 4.29497e+07)
		return -1;
	in *= 100;
	o->ChargerChargingVariable.MeteringValue = in;
	return 0;
}

int candb_decode_csm_charger_EVSEPresentVoltage_0x80040002(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerChargingVariable.EVSEPresentVoltage);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEPresentVoltage_0x80040002(can_csm_charger_t *o, float64 in) {
	o->ChargerChargingVariable.EVSEPresentVoltage = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerChargingVariable.EVSEPresentVoltage = in;
	return 0;
}

int candb_decode_csm_charger_EVSEPresentCurrent_0x80040002(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerChargingVariable.EVSEPresentCurrent);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEPresentCurrent_0x80040002(can_csm_charger_t *o, float64 in) {
	o->ChargerChargingVariable.EVSEPresentCurrent = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerChargingVariable.EVSEPresentCurrent = in;
	return 0;
}

static int pack_csm_charger_ChargerChargingService_0x80040003(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* DepartureTime: start-bit 32, length 32, endianess intel, scaling 0.2, offset 0 */
	x = ((uint32)(o->ChargerChargingService.DepartureTime)) & 0xffffffff;
	x <<= 32; 
	i |= x;
	/* TargetSoc: start-bit 16, length 8, endianess intel, scaling 0.1, offset 0 */
	x = ((uint8)(o->ChargerChargingService.TargetSoc)) & 0xff;
	x <<= 16; 
	i |= x;
	/* MinimumSoc: start-bit 24, length 8, endianess intel, scaling 0.1, offset 0 */
	x = ((uint8)(o->ChargerChargingService.MinimumSoc)) & 0xff;
	x <<= 24; 
	i |= x;
	/* BPTChannel: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerChargingService.BPTChannel)) & 0xf;
	x <<= 4; 
	i |= x;
	/* GenerateMode: start-bit 0, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerChargingService.GenerateMode)) & 0x3;
	i |= x;
	/* GridCodeIslandingDetectionMethod: start-bit 2, length 2, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerChargingService.GridCodeIslandingDetectionMethod)) & 0x3;
	x <<= 2; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerChargingService_0x80040003(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* DepartureTime: start-bit 32, length 32, endianess intel, scaling 0.2, offset 0 */
	x = (i >> 32) & 0xffffffff;
	o->ChargerChargingService.DepartureTime = x;
	/* TargetSoc: start-bit 16, length 8, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xff;
	o->ChargerChargingService.TargetSoc = x;
	/* MinimumSoc: start-bit 24, length 8, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 24) & 0xff;
	o->ChargerChargingService.MinimumSoc = x;
	/* BPTChannel: start-bit 4, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 4) & 0xf;
	o->ChargerChargingService.BPTChannel = x;
	/* GenerateMode: start-bit 0, length 2, endianess intel, scaling 1, offset 0 */
	x = i & 0x3;
	o->ChargerChargingService.GenerateMode = x;
	/* GridCodeIslandingDetectionMethod: start-bit 2, length 2, endianess intel, scaling 1, offset 0 */
	x = (i >> 2) & 0x3;
	o->ChargerChargingService.GridCodeIslandingDetectionMethod = x;
	return 0;
}

int candb_decode_csm_charger_DepartureTime_0x80040003(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerChargingService.DepartureTime);
	rval *= 0.2;
	if (rval <= 8.58993e+08) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_DepartureTime_0x80040003(can_csm_charger_t *o, float64 in) {
	o->ChargerChargingService.DepartureTime = 0;
	if (in > 8.58993e+08)
		return -1;
	in *= 5;
	o->ChargerChargingService.DepartureTime = in;
	return 0;
}

int candb_decode_csm_charger_TargetSoc_0x80040003(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerChargingService.TargetSoc);
	rval *= 0.1;
	if (rval <= 25.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_TargetSoc_0x80040003(can_csm_charger_t *o, float64 in) {
	o->ChargerChargingService.TargetSoc = 0;
	if (in > 25.5)
		return -1;
	in *= 10;
	o->ChargerChargingService.TargetSoc = in;
	return 0;
}

int candb_decode_csm_charger_MinimumSoc_0x80040003(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerChargingService.MinimumSoc);
	rval *= 0.1;
	if (rval <= 25.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_MinimumSoc_0x80040003(can_csm_charger_t *o, float64 in) {
	o->ChargerChargingService.MinimumSoc = 0;
	if (in > 25.5)
		return -1;
	in *= 10;
	o->ChargerChargingService.MinimumSoc = in;
	return 0;
}

int candb_decode_csm_charger_BPTChannel_0x80040003(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerChargingService.BPTChannel);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_BPTChannel_0x80040003(can_csm_charger_t *o, uint8 in) {
	o->ChargerChargingService.BPTChannel = in;
	return 0;
}

int candb_decode_csm_charger_GenerateMode_0x80040003(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerChargingService.GenerateMode);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_GenerateMode_0x80040003(can_csm_charger_t *o, uint8 in) {
	o->ChargerChargingService.GenerateMode = in;
	return 0;
}

int candb_decode_csm_charger_GridCodeIslandingDetectionMethod_0x80040003(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerChargingService.GridCodeIslandingDetectionMethod);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_GridCodeIslandingDetectionMethod_0x80040003(can_csm_charger_t *o, uint8 in) {
	o->ChargerChargingService.GridCodeIslandingDetectionMethod = in;
	return 0;
}

static int pack_csm_charger_ChargerDcChargeParameter1_0x80040006(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSEMaximumCurrentLimit: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcChargeParameter1.EVSEMaximumCurrentLimit)) & 0xffff;
	i |= x;
	/* EVSEMaximumVoltageLimit: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcChargeParameter1.EVSEMaximumVoltageLimit)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSEMinimumCurrentLimit: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcChargeParameter1.EVSEMinimumCurrentLimit)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* EVSEMinimumVoltagelimit: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcChargeParameter1.EVSEMinimumVoltagelimit)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerDcChargeParameter1_0x80040006(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSEMaximumCurrentLimit: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerDcChargeParameter1.EVSEMaximumCurrentLimit = x;
	/* EVSEMaximumVoltageLimit: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerDcChargeParameter1.EVSEMaximumVoltageLimit = x;
	/* EVSEMinimumCurrentLimit: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerDcChargeParameter1.EVSEMinimumCurrentLimit = x;
	/* EVSEMinimumVoltagelimit: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->ChargerDcChargeParameter1.EVSEMinimumVoltagelimit = x;
	return 0;
}

int candb_decode_csm_charger_EVSEMaximumCurrentLimit_0x80040006(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcChargeParameter1.EVSEMaximumCurrentLimit);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaximumCurrentLimit_0x80040006(can_csm_charger_t *o, float64 in) {
	o->ChargerDcChargeParameter1.EVSEMaximumCurrentLimit = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerDcChargeParameter1.EVSEMaximumCurrentLimit = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMaximumVoltageLimit_0x80040006(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcChargeParameter1.EVSEMaximumVoltageLimit);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaximumVoltageLimit_0x80040006(can_csm_charger_t *o, float64 in) {
	o->ChargerDcChargeParameter1.EVSEMaximumVoltageLimit = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerDcChargeParameter1.EVSEMaximumVoltageLimit = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMinimumCurrentLimit_0x80040006(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcChargeParameter1.EVSEMinimumCurrentLimit);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMinimumCurrentLimit_0x80040006(can_csm_charger_t *o, float64 in) {
	o->ChargerDcChargeParameter1.EVSEMinimumCurrentLimit = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerDcChargeParameter1.EVSEMinimumCurrentLimit = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMinimumVoltagelimit_0x80040006(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcChargeParameter1.EVSEMinimumVoltagelimit);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMinimumVoltagelimit_0x80040006(can_csm_charger_t *o, float64 in) {
	o->ChargerDcChargeParameter1.EVSEMinimumVoltagelimit = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerDcChargeParameter1.EVSEMinimumVoltagelimit = in;
	return 0;
}

static int pack_csm_charger_ChargerDcChargeParameter2_0x80040007(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSEPeakCurrentRipple: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcChargeParameter2.EVSEPeakCurrentRipple)) & 0xffff;
	i |= x;
	/* EVSEMaximumPowerLimit: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcChargeParameter2.EVSEMaximumPowerLimit)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSECurrentRegulationTolerance: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcChargeParameter2.EVSECurrentRegulationTolerance)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* EVSEEnergyToBeDelivered: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->ChargerDcChargeParameter2.EVSEEnergyToBeDelivered)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerDcChargeParameter2_0x80040007(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSEPeakCurrentRipple: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerDcChargeParameter2.EVSEPeakCurrentRipple = x;
	/* EVSEMaximumPowerLimit: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerDcChargeParameter2.EVSEMaximumPowerLimit = x;
	/* EVSECurrentRegulationTolerance: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerDcChargeParameter2.EVSECurrentRegulationTolerance = x;
	/* EVSEEnergyToBeDelivered: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->ChargerDcChargeParameter2.EVSEEnergyToBeDelivered = x;
	return 0;
}

int candb_decode_csm_charger_EVSEPeakCurrentRipple_0x80040007(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcChargeParameter2.EVSEPeakCurrentRipple);
	rval *= 0.1;
	if (rval <= 4000) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEPeakCurrentRipple_0x80040007(can_csm_charger_t *o, float64 in) {
	o->ChargerDcChargeParameter2.EVSEPeakCurrentRipple = 0;
	if (in > 4000)
		return -1;
	in *= 10;
	o->ChargerDcChargeParameter2.EVSEPeakCurrentRipple = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMaximumPowerLimit_0x80040007(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcChargeParameter2.EVSEMaximumPowerLimit);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaximumPowerLimit_0x80040007(can_csm_charger_t *o, float64 in) {
	o->ChargerDcChargeParameter2.EVSEMaximumPowerLimit = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerDcChargeParameter2.EVSEMaximumPowerLimit = in;
	return 0;
}

int candb_decode_csm_charger_EVSECurrentRegulationTolerance_0x80040007(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcChargeParameter2.EVSECurrentRegulationTolerance);
	rval *= 0.1;
	if (rval <= 4000) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSECurrentRegulationTolerance_0x80040007(can_csm_charger_t *o, float64 in) {
	o->ChargerDcChargeParameter2.EVSECurrentRegulationTolerance = 0;
	if (in > 4000)
		return -1;
	in *= 10;
	o->ChargerDcChargeParameter2.EVSECurrentRegulationTolerance = in;
	return 0;
}

int candb_decode_csm_charger_EVSEEnergyToBeDelivered_0x80040007(const can_csm_charger_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->ChargerDcChargeParameter2.EVSEEnergyToBeDelivered);
	if (rval <= 2000) {
		*out = rval;
		return 0;
	} else {
		*out = (uint16)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEEnergyToBeDelivered_0x80040007(can_csm_charger_t *o, uint16 in) {
	o->ChargerDcChargeParameter2.EVSEEnergyToBeDelivered = 0;
	if (in > 2000)
		return -1;
	o->ChargerDcChargeParameter2.EVSEEnergyToBeDelivered = in;
	return 0;
}

static int pack_csm_charger_ChargerDcDischargeParam_0x80040008(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* MaximumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcDischargeParam.MaximumDischargePower)) & 0xffff;
	i |= x;
	/* MinimumDischargePower: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcDischargeParam.MinimumDischargePower)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* MaximumDischargeCurrent: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcDischargeParam.MaximumDischargeCurrent)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* MinimumDischargeCurrent: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerDcDischargeParam.MinimumDischargeCurrent)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerDcDischargeParam_0x80040008(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* MaximumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerDcDischargeParam.MaximumDischargePower = x;
	/* MinimumDischargePower: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerDcDischargeParam.MinimumDischargePower = x;
	/* MaximumDischargeCurrent: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerDcDischargeParam.MaximumDischargeCurrent = x;
	/* MinimumDischargeCurrent: start-bit 48, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->ChargerDcDischargeParam.MinimumDischargeCurrent = x;
	return 0;
}

int candb_decode_csm_charger_MaximumDischargePower_0x80040008(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcDischargeParam.MaximumDischargePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_MaximumDischargePower_0x80040008(can_csm_charger_t *o, float64 in) {
	o->ChargerDcDischargeParam.MaximumDischargePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerDcDischargeParam.MaximumDischargePower = in;
	return 0;
}

int candb_decode_csm_charger_MinimumDischargePower_0x80040008(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcDischargeParam.MinimumDischargePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_MinimumDischargePower_0x80040008(can_csm_charger_t *o, float64 in) {
	o->ChargerDcDischargeParam.MinimumDischargePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerDcDischargeParam.MinimumDischargePower = in;
	return 0;
}

int candb_decode_csm_charger_MaximumDischargeCurrent_0x80040008(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcDischargeParam.MaximumDischargeCurrent);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_MaximumDischargeCurrent_0x80040008(can_csm_charger_t *o, float64 in) {
	o->ChargerDcDischargeParam.MaximumDischargeCurrent = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerDcDischargeParam.MaximumDischargeCurrent = in;
	return 0;
}

int candb_decode_csm_charger_MinimumDischargeCurrent_0x80040008(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerDcDischargeParam.MinimumDischargeCurrent);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_MinimumDischargeCurrent_0x80040008(can_csm_charger_t *o, float64 in) {
	o->ChargerDcDischargeParam.MinimumDischargeCurrent = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerDcDischargeParam.MinimumDischargeCurrent = in;
	return 0;
}

static int pack_csm_charger_ChargerAcChargeParam_0x80040009(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSEMaxCurrent: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcChargeParam.EVSEMaxCurrent)) & 0xffff;
	i |= x;
	/* EVSENominalVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcChargeParam.EVSENominalVoltage)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSENominalFrequency: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->ChargerAcChargeParam.EVSENominalFrequency)) & 0xffff;
	x <<= 32; 
	i |= x;
	/* EVSETargetFrequency: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->ChargerAcChargeParam.EVSETargetFrequency)) & 0xffff;
	x <<= 48; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcChargeParam_0x80040009(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSEMaxCurrent: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcChargeParam.EVSEMaxCurrent = x;
	/* EVSENominalVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcChargeParam.EVSENominalVoltage = x;
	/* EVSENominalFrequency: start-bit 32, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcChargeParam.EVSENominalFrequency = x;
	/* EVSETargetFrequency: start-bit 48, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 48) & 0xffff;
	o->ChargerAcChargeParam.EVSETargetFrequency = x;
	return 0;
}

int candb_decode_csm_charger_EVSEMaxCurrent_0x80040009(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcChargeParam.EVSEMaxCurrent);
	rval *= 0.1;
	if (rval <= 4000) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaxCurrent_0x80040009(can_csm_charger_t *o, float64 in) {
	o->ChargerAcChargeParam.EVSEMaxCurrent = 0;
	if (in > 4000)
		return -1;
	in *= 10;
	o->ChargerAcChargeParam.EVSEMaxCurrent = in;
	return 0;
}

int candb_decode_csm_charger_EVSENominalVoltage_0x80040009(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcChargeParam.EVSENominalVoltage);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSENominalVoltage_0x80040009(can_csm_charger_t *o, float64 in) {
	o->ChargerAcChargeParam.EVSENominalVoltage = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerAcChargeParam.EVSENominalVoltage = in;
	return 0;
}

int candb_decode_csm_charger_EVSENominalFrequency_0x80040009(const can_csm_charger_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->ChargerAcChargeParam.EVSENominalFrequency);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_EVSENominalFrequency_0x80040009(can_csm_charger_t *o, uint16 in) {
	o->ChargerAcChargeParam.EVSENominalFrequency = in;
	return 0;
}

int candb_decode_csm_charger_EVSETargetFrequency_0x80040009(const can_csm_charger_t *o, uint16 *out) {
	uint16 rval = (uint16)(o->ChargerAcChargeParam.EVSETargetFrequency);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_EVSETargetFrequency_0x80040009(can_csm_charger_t *o, uint16 in) {
	o->ChargerAcChargeParam.EVSETargetFrequency = in;
	return 0;
}

static int pack_csm_charger_ChargerAcPresentActivePower_0x8004000b(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSEPresentActivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcPresentActivePower.EVSEPresentActivePower)) & 0xffff;
	i |= x;
	/* EVSEPresentActivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcPresentActivePower.EVSEPresentActivePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSEPresentActivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcPresentActivePower.EVSEPresentActivePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcPresentActivePower_0x8004000b(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSEPresentActivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcPresentActivePower.EVSEPresentActivePower = x;
	/* EVSEPresentActivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcPresentActivePower.EVSEPresentActivePower_L2 = x;
	/* EVSEPresentActivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcPresentActivePower.EVSEPresentActivePower_L3 = x;
	return 0;
}

int candb_decode_csm_charger_EVSEPresentActivePower_0x8004000b(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcPresentActivePower.EVSEPresentActivePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEPresentActivePower_0x8004000b(can_csm_charger_t *o, float64 in) {
	o->ChargerAcPresentActivePower.EVSEPresentActivePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcPresentActivePower.EVSEPresentActivePower = in;
	return 0;
}

int candb_decode_csm_charger_EVSEPresentActivePower_L2_0x8004000b(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcPresentActivePower.EVSEPresentActivePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEPresentActivePower_L2_0x8004000b(can_csm_charger_t *o, float64 in) {
	o->ChargerAcPresentActivePower.EVSEPresentActivePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcPresentActivePower.EVSEPresentActivePower_L2 = in;
	return 0;
}

int candb_decode_csm_charger_EVSEPresentActivePower_L3_0x8004000b(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcPresentActivePower.EVSEPresentActivePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEPresentActivePower_L3_0x8004000b(can_csm_charger_t *o, float64 in) {
	o->ChargerAcPresentActivePower.EVSEPresentActivePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcPresentActivePower.EVSEPresentActivePower_L3 = in;
	return 0;
}

static int pack_csm_charger_ChargerAcTargetActivePower_0x8004000c(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSETargetActivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcTargetActivePower.EVSETargetActivePower)) & 0xffff;
	i |= x;
	/* EVSETargetActivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcTargetActivePower.EVSETargetActivePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSETargetActivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcTargetActivePower.EVSETargetActivePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcTargetActivePower_0x8004000c(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSETargetActivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcTargetActivePower.EVSETargetActivePower = x;
	/* EVSETargetActivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcTargetActivePower.EVSETargetActivePower_L2 = x;
	/* EVSETargetActivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcTargetActivePower.EVSETargetActivePower_L3 = x;
	return 0;
}

int candb_decode_csm_charger_EVSETargetActivePower_0x8004000c(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcTargetActivePower.EVSETargetActivePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSETargetActivePower_0x8004000c(can_csm_charger_t *o, float64 in) {
	o->ChargerAcTargetActivePower.EVSETargetActivePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcTargetActivePower.EVSETargetActivePower = in;
	return 0;
}

int candb_decode_csm_charger_EVSETargetActivePower_L2_0x8004000c(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcTargetActivePower.EVSETargetActivePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSETargetActivePower_L2_0x8004000c(can_csm_charger_t *o, float64 in) {
	o->ChargerAcTargetActivePower.EVSETargetActivePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcTargetActivePower.EVSETargetActivePower_L2 = in;
	return 0;
}

int candb_decode_csm_charger_EVSETargetActivePower_L3_0x8004000c(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcTargetActivePower.EVSETargetActivePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSETargetActivePower_L3_0x8004000c(can_csm_charger_t *o, float64 in) {
	o->ChargerAcTargetActivePower.EVSETargetActivePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcTargetActivePower.EVSETargetActivePower_L3 = in;
	return 0;
}

static int pack_csm_charger_ChargerAcTargetReactivePower_0x8004000d(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSETargetReactivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcTargetReactivePower.EVSETargetReactivePower)) & 0xffff;
	i |= x;
	/* EVSETargetReactivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSETargetReactivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcTargetReactivePower_0x8004000d(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSETargetReactivePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcTargetReactivePower.EVSETargetReactivePower = x;
	/* EVSETargetReactivePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L2 = x;
	/* EVSETargetReactivePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L3 = x;
	return 0;
}

int candb_decode_csm_charger_EVSETargetReactivePower_0x8004000d(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcTargetReactivePower.EVSETargetReactivePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSETargetReactivePower_0x8004000d(can_csm_charger_t *o, float64 in) {
	o->ChargerAcTargetReactivePower.EVSETargetReactivePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcTargetReactivePower.EVSETargetReactivePower = in;
	return 0;
}

int candb_decode_csm_charger_EVSETargetReactivePower_L2_0x8004000d(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSETargetReactivePower_L2_0x8004000d(can_csm_charger_t *o, float64 in) {
	o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L2 = in;
	return 0;
}

int candb_decode_csm_charger_EVSETargetReactivePower_L3_0x8004000d(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSETargetReactivePower_L3_0x8004000d(can_csm_charger_t *o, float64 in) {
	o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcTargetReactivePower.EVSETargetReactivePower_L3 = in;
	return 0;
}

static int pack_csm_charger_ChargerAcMaximumChargePower_0x8004000e(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSEMaximumChargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMaximumChargePower.EVSEMaximumChargePower)) & 0xffff;
	i |= x;
	/* EVSEMaximumChargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSEMaximumChargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcMaximumChargePower_0x8004000e(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSEMaximumChargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcMaximumChargePower.EVSEMaximumChargePower = x;
	/* EVSEMaximumChargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L2 = x;
	/* EVSEMaximumChargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L3 = x;
	return 0;
}

int candb_decode_csm_charger_EVSEMaximumChargePower_0x8004000e(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMaximumChargePower.EVSEMaximumChargePower);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaximumChargePower_0x8004000e(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMaximumChargePower.EVSEMaximumChargePower = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerAcMaximumChargePower.EVSEMaximumChargePower = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMaximumChargePower_L2_0x8004000e(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L2);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaximumChargePower_L2_0x8004000e(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L2 = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L2 = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMaximumChargePower_L3_0x8004000e(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L3);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaximumChargePower_L3_0x8004000e(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L3 = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerAcMaximumChargePower.EVSEMaximumChargePower_L3 = in;
	return 0;
}

static int pack_csm_charger_ChargerAcMinimumChargePower_0x8004000f(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSEMinimumChargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMinimumChargePower.EVSEMinimumChargePower)) & 0xffff;
	i |= x;
	/* EVSEMinimumChargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSEMinimumChargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcMinimumChargePower_0x8004000f(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSEMinimumChargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcMinimumChargePower.EVSEMinimumChargePower = x;
	/* EVSEMinimumChargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L2 = x;
	/* EVSEMinimumChargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L3 = x;
	return 0;
}

int candb_decode_csm_charger_EVSEMinimumChargePower_0x8004000f(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMinimumChargePower.EVSEMinimumChargePower);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMinimumChargePower_0x8004000f(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMinimumChargePower.EVSEMinimumChargePower = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerAcMinimumChargePower.EVSEMinimumChargePower = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMinimumChargePower_L2_0x8004000f(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L2);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMinimumChargePower_L2_0x8004000f(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L2 = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L2 = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMinimumChargePower_L3_0x8004000f(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L3);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMinimumChargePower_L3_0x8004000f(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L3 = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerAcMinimumChargePower.EVSEMinimumChargePower_L3 = in;
	return 0;
}

static int pack_csm_charger_ChargerAcMaximumDischargePower_0x80040010(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSEMaximumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower)) & 0xffff;
	i |= x;
	/* EVSEMaximumDischargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSEMaximumDischargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcMaximumDischargePower_0x80040010(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSEMaximumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower = x;
	/* EVSEMaximumDischargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L2 = x;
	/* EVSEMaximumDischargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L3 = x;
	return 0;
}

int candb_decode_csm_charger_EVSEMaximumDischargePower_0x80040010(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaximumDischargePower_0x80040010(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMaximumDischargePower_L2_0x80040010(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaximumDischargePower_L2_0x80040010(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L2 = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMaximumDischargePower_L3_0x80040010(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMaximumDischargePower_L3_0x80040010(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcMaximumDischargePower.EVSEMaximumDischargePower_L3 = in;
	return 0;
}

static int pack_csm_charger_ChargerAcMinimumDischargePower_0x80040011(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* EVSEMinimumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower)) & 0xffff;
	i |= x;
	/* EVSEMinimumDischargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L2)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* EVSEMinimumDischargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L3)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcMinimumDischargePower_0x80040011(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* EVSEMinimumDischargePower: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower = x;
	/* EVSEMinimumDischargePower_L2: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L2 = x;
	/* EVSEMinimumDischargePower_L3: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L3 = x;
	return 0;
}

int candb_decode_csm_charger_EVSEMinimumDischargePower_0x80040011(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMinimumDischargePower_0x80040011(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMinimumDischargePower_L2_0x80040011(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L2);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMinimumDischargePower_L2_0x80040011(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L2 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L2 = in;
	return 0;
}

int candb_decode_csm_charger_EVSEMinimumDischargePower_L3_0x80040011(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L3);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEMinimumDischargePower_L3_0x80040011(can_csm_charger_t *o, float64 in) {
	o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L3 = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcMinimumDischargePower.EVSEMinimumDischargePower_L3 = in;
	return 0;
}

static int pack_csm_charger_ChargerAcChargingSafety_0x80040012(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* MaximumPowerAsymmetry: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcChargingSafety.MaximumPowerAsymmetry)) & 0xffff;
	i |= x;
	/* EVSEPowerRampLimitation: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcChargingSafety.EVSEPowerRampLimitation)) & 0xffff;
	x <<= 16; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcChargingSafety_0x80040012(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* MaximumPowerAsymmetry: start-bit 0, length 16, endianess intel, scaling 0.1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcChargingSafety.MaximumPowerAsymmetry = x;
	/* EVSEPowerRampLimitation: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcChargingSafety.EVSEPowerRampLimitation = x;
	return 0;
}

int candb_decode_csm_charger_MaximumPowerAsymmetry_0x80040012(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcChargingSafety.MaximumPowerAsymmetry);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_MaximumPowerAsymmetry_0x80040012(can_csm_charger_t *o, float64 in) {
	o->ChargerAcChargingSafety.MaximumPowerAsymmetry = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerAcChargingSafety.MaximumPowerAsymmetry = in;
	return 0;
}

int candb_decode_csm_charger_EVSEPowerRampLimitation_0x80040012(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcChargingSafety.EVSEPowerRampLimitation);
	rval *= 0.1;
	if (rval <= 6553.5) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_EVSEPowerRampLimitation_0x80040012(can_csm_charger_t *o, float64 in) {
	o->ChargerAcChargingSafety.EVSEPowerRampLimitation = 0;
	if (in > 6553.5)
		return -1;
	in *= 10;
	o->ChargerAcChargingSafety.EVSEPowerRampLimitation = in;
	return 0;
}

static int pack_csm_charger_ChargerAcFrtLvrt_0x80040020(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* LVRTMomentaryCessationEnable: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->ChargerAcFrtLvrt.LVRTMomentaryCessationEnable)) & 0xffff;
	i |= x;
	/* LVRTMomentaryCessationVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcFrtLvrt.LVRTMomentaryCessationVoltage)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* LVRTMomentaryCessationRecoveryV: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcFrtLvrt.LVRTMomentaryCessationRecoveryV)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcFrtLvrt_0x80040020(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* LVRTMomentaryCessationEnable: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcFrtLvrt.LVRTMomentaryCessationEnable = x;
	/* LVRTMomentaryCessationVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcFrtLvrt.LVRTMomentaryCessationVoltage = x;
	/* LVRTMomentaryCessationRecoveryV: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcFrtLvrt.LVRTMomentaryCessationRecoveryV = x;
	return 0;
}

int candb_decode_csm_charger_LVRTMomentaryCessationEnable_0x80040020(const can_csm_charger_t *o, sint16 *out) {
	sint16 rval = (sint16)(o->ChargerAcFrtLvrt.LVRTMomentaryCessationEnable);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_LVRTMomentaryCessationEnable_0x80040020(can_csm_charger_t *o, sint16 in) {
	o->ChargerAcFrtLvrt.LVRTMomentaryCessationEnable = in;
	return 0;
}

int candb_decode_csm_charger_LVRTMomentaryCessationVoltage_0x80040020(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcFrtLvrt.LVRTMomentaryCessationVoltage);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_LVRTMomentaryCessationVoltage_0x80040020(can_csm_charger_t *o, float64 in) {
	o->ChargerAcFrtLvrt.LVRTMomentaryCessationVoltage = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcFrtLvrt.LVRTMomentaryCessationVoltage = in;
	return 0;
}

int candb_decode_csm_charger_LVRTMomentaryCessationRecoveryV_0x80040020(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcFrtLvrt.LVRTMomentaryCessationRecoveryV);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_LVRTMomentaryCessationRecoveryV_0x80040020(can_csm_charger_t *o, float64 in) {
	o->ChargerAcFrtLvrt.LVRTMomentaryCessationRecoveryV = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcFrtLvrt.LVRTMomentaryCessationRecoveryV = in;
	return 0;
}

static int pack_csm_charger_ChargerAcFrtHvrt_0x80040021(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* HVRTMomentaryCessationEnable: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->ChargerAcFrtHvrt.HVRTMomentaryCessationEnable)) & 0xffff;
	i |= x;
	/* HVRTMomentaryCessationVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcFrtHvrt.HVRTMomentaryCessationVoltage)) & 0xffff;
	x <<= 16; 
	i |= x;
	/* HVRTMomentaryCessationRecoveryV: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = ((uint16)(o->ChargerAcFrtHvrt.HVRTMomentaryCessationRecoveryV)) & 0xffff;
	x <<= 32; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcFrtHvrt_0x80040021(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* HVRTMomentaryCessationEnable: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcFrtHvrt.HVRTMomentaryCessationEnable = x;
	/* HVRTMomentaryCessationVoltage: start-bit 16, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcFrtHvrt.HVRTMomentaryCessationVoltage = x;
	/* HVRTMomentaryCessationRecoveryV: start-bit 32, length 16, endianess intel, scaling 0.1, offset 0 */
	x = (i >> 32) & 0xffff;
	o->ChargerAcFrtHvrt.HVRTMomentaryCessationRecoveryV = x;
	return 0;
}

int candb_decode_csm_charger_HVRTMomentaryCessationEnable_0x80040021(const can_csm_charger_t *o, sint16 *out) {
	sint16 rval = (sint16)(o->ChargerAcFrtHvrt.HVRTMomentaryCessationEnable);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_HVRTMomentaryCessationEnable_0x80040021(can_csm_charger_t *o, sint16 in) {
	o->ChargerAcFrtHvrt.HVRTMomentaryCessationEnable = in;
	return 0;
}

int candb_decode_csm_charger_HVRTMomentaryCessationVoltage_0x80040021(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcFrtHvrt.HVRTMomentaryCessationVoltage);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_HVRTMomentaryCessationVoltage_0x80040021(can_csm_charger_t *o, float64 in) {
	o->ChargerAcFrtHvrt.HVRTMomentaryCessationVoltage = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcFrtHvrt.HVRTMomentaryCessationVoltage = in;
	return 0;
}

int candb_decode_csm_charger_HVRTMomentaryCessationRecoveryV_0x80040021(const can_csm_charger_t *o, float64 *out) {
	float64 rval = (float64)(o->ChargerAcFrtHvrt.HVRTMomentaryCessationRecoveryV);
	rval *= 0.1;
	if ((rval >= -3276.8) && (rval <= 3276.7)) {
		*out = rval;
		return 0;
	} else {
		*out = (float64)0;
		return -1;
	}
}

int candb_encode_csm_charger_HVRTMomentaryCessationRecoveryV_0x80040021(can_csm_charger_t *o, float64 in) {
	o->ChargerAcFrtHvrt.HVRTMomentaryCessationRecoveryV = 0;
	if (in < -3276.8)
		return -1;
	if (in > 3276.7)
		return -1;
	in *= 10;
	o->ChargerAcFrtHvrt.HVRTMomentaryCessationRecoveryV = in;
	return 0;
}

static int pack_csm_charger_ChargerAcFrtReactivePower_0x80040022(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* ReactivePowerResponseTimeEnable: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->ChargerAcFrtReactivePower.ReactivePowerResponseTimeEnable)) & 0xffff;
	i |= x;
	/* ReactivePowerControlResponse: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = ((uint16)(o->ChargerAcFrtReactivePower.ReactivePowerControlResponse)) & 0xffff;
	x <<= 16; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerAcFrtReactivePower_0x80040022(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* ReactivePowerResponseTimeEnable: start-bit 0, length 16, endianess intel, scaling 1, offset 0 */
	x = i & 0xffff;
	o->ChargerAcFrtReactivePower.ReactivePowerResponseTimeEnable = x;
	/* ReactivePowerControlResponse: start-bit 16, length 16, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0xffff;
	o->ChargerAcFrtReactivePower.ReactivePowerControlResponse = x;
	return 0;
}

int candb_decode_csm_charger_ReactivePowerResponseTimeEnable_0x80040022(const can_csm_charger_t *o, sint16 *out) {
	sint16 rval = (sint16)(o->ChargerAcFrtReactivePower.ReactivePowerResponseTimeEnable);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_ReactivePowerResponseTimeEnable_0x80040022(can_csm_charger_t *o, sint16 in) {
	o->ChargerAcFrtReactivePower.ReactivePowerResponseTimeEnable = in;
	return 0;
}

int candb_decode_csm_charger_ReactivePowerControlResponse_0x80040022(const can_csm_charger_t *o, sint16 *out) {
	sint16 rval = (sint16)(o->ChargerAcFrtReactivePower.ReactivePowerControlResponse);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_ReactivePowerControlResponse_0x80040022(can_csm_charger_t *o, sint16 in) {
	o->ChargerAcFrtReactivePower.ReactivePowerControlResponse = in;
	return 0;
}

static int pack_csm_charger_ChargerDateTime_0x800401f1(can_csm_charger_t *o, uint64 *data) {
	register uint64 x;
	register uint64 i = 0;
	/* Year: start-bit 0, length 7, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerDateTime.Year)) & 0x7f;
	i |= x;
	/* Minutes: start-bit 32, length 6, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerDateTime.Minutes)) & 0x3f;
	x <<= 32; 
	i |= x;
	/* Seconds: start-bit 40, length 6, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerDateTime.Seconds)) & 0x3f;
	x <<= 40; 
	i |= x;
	/* Day: start-bit 16, length 5, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerDateTime.Day)) & 0x1f;
	x <<= 16; 
	i |= x;
	/* Hours: start-bit 24, length 5, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerDateTime.Hours)) & 0x1f;
	x <<= 24; 
	i |= x;
	/* Month: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = ((uint8)(o->ChargerDateTime.Month)) & 0xf;
	x <<= 8; 
	i |= x;
	*data = (i);
	return 0;
}

static int unpack_csm_charger_ChargerDateTime_0x800401f1(can_csm_charger_t *o, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	register uint64 x;
	register uint64 i = (data);
	if (dlc < 8)
		return -1;
	/* Year: start-bit 0, length 7, endianess intel, scaling 1, offset 0 */
	x = i & 0x7f;
	o->ChargerDateTime.Year = x;
	/* Minutes: start-bit 32, length 6, endianess intel, scaling 1, offset 0 */
	x = (i >> 32) & 0x3f;
	o->ChargerDateTime.Minutes = x;
	/* Seconds: start-bit 40, length 6, endianess intel, scaling 1, offset 0 */
	x = (i >> 40) & 0x3f;
	o->ChargerDateTime.Seconds = x;
	/* Day: start-bit 16, length 5, endianess intel, scaling 1, offset 0 */
	x = (i >> 16) & 0x1f;
	o->ChargerDateTime.Day = x;
	/* Hours: start-bit 24, length 5, endianess intel, scaling 1, offset 0 */
	x = (i >> 24) & 0x1f;
	o->ChargerDateTime.Hours = x;
	/* Month: start-bit 8, length 4, endianess intel, scaling 1, offset 0 */
	x = (i >> 8) & 0xf;
	o->ChargerDateTime.Month = x;
	return 0;
}

int candb_decode_csm_charger_Year_0x800401f1(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerDateTime.Year);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_Year_0x800401f1(can_csm_charger_t *o, uint8 in) {
	o->ChargerDateTime.Year = in;
	return 0;
}

int candb_decode_csm_charger_Minutes_0x800401f1(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerDateTime.Minutes);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_Minutes_0x800401f1(can_csm_charger_t *o, uint8 in) {
	o->ChargerDateTime.Minutes = in;
	return 0;
}

int candb_decode_csm_charger_Seconds_0x800401f1(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerDateTime.Seconds);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_Seconds_0x800401f1(can_csm_charger_t *o, uint8 in) {
	o->ChargerDateTime.Seconds = in;
	return 0;
}

int candb_decode_csm_charger_Day_0x800401f1(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerDateTime.Day);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_Day_0x800401f1(can_csm_charger_t *o, uint8 in) {
	o->ChargerDateTime.Day = in;
	return 0;
}

int candb_decode_csm_charger_Hours_0x800401f1(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerDateTime.Hours);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_Hours_0x800401f1(can_csm_charger_t *o, uint8 in) {
	o->ChargerDateTime.Hours = in;
	return 0;
}

int candb_decode_csm_charger_Month_0x800401f1(const can_csm_charger_t *o, uint8 *out) {
	uint8 rval = (uint8)(o->ChargerDateTime.Month);
	*out = rval;
	return 0;
}

int candb_encode_csm_charger_Month_0x800401f1(can_csm_charger_t *o, uint8 in) {
	o->ChargerDateTime.Month = in;
	return 0;
}

int candb_csm_charger_unpack_message(can_csm_charger_t *o, const unsigned long id, uint64 data, uint8 dlc, dbcc_time_stamp_t time_stamp) {
	switch (id) {
	case 0x80040001: return unpack_csm_charger_ChargerStatus_0x80040001(o, data, dlc, time_stamp);
	case 0x80040002: return unpack_csm_charger_ChargerChargingVariable_0x80040002(o, data, dlc, time_stamp);
	case 0x80040003: return unpack_csm_charger_ChargerChargingService_0x80040003(o, data, dlc, time_stamp);
	case 0x80040006: return unpack_csm_charger_ChargerDcChargeParameter1_0x80040006(o, data, dlc, time_stamp);
	case 0x80040007: return unpack_csm_charger_ChargerDcChargeParameter2_0x80040007(o, data, dlc, time_stamp);
	case 0x80040008: return unpack_csm_charger_ChargerDcDischargeParam_0x80040008(o, data, dlc, time_stamp);
	case 0x80040009: return unpack_csm_charger_ChargerAcChargeParam_0x80040009(o, data, dlc, time_stamp);
	case 0x8004000b: return unpack_csm_charger_ChargerAcPresentActivePower_0x8004000b(o, data, dlc, time_stamp);
	case 0x8004000c: return unpack_csm_charger_ChargerAcTargetActivePower_0x8004000c(o, data, dlc, time_stamp);
	case 0x8004000d: return unpack_csm_charger_ChargerAcTargetReactivePower_0x8004000d(o, data, dlc, time_stamp);
	case 0x8004000e: return unpack_csm_charger_ChargerAcMaximumChargePower_0x8004000e(o, data, dlc, time_stamp);
	case 0x8004000f: return unpack_csm_charger_ChargerAcMinimumChargePower_0x8004000f(o, data, dlc, time_stamp);
	case 0x80040010: return unpack_csm_charger_ChargerAcMaximumDischargePower_0x80040010(o, data, dlc, time_stamp);
	case 0x80040011: return unpack_csm_charger_ChargerAcMinimumDischargePower_0x80040011(o, data, dlc, time_stamp);
	case 0x80040012: return unpack_csm_charger_ChargerAcChargingSafety_0x80040012(o, data, dlc, time_stamp);
	case 0x80040020: return unpack_csm_charger_ChargerAcFrtLvrt_0x80040020(o, data, dlc, time_stamp);
	case 0x80040021: return unpack_csm_charger_ChargerAcFrtHvrt_0x80040021(o, data, dlc, time_stamp);
	case 0x80040022: return unpack_csm_charger_ChargerAcFrtReactivePower_0x80040022(o, data, dlc, time_stamp);
	case 0x800401f1: return unpack_csm_charger_ChargerDateTime_0x800401f1(o, data, dlc, time_stamp);
	default: break; 
	}
	return -1; 
}

int candb_csm_charger_pack_message(can_csm_charger_t *o, const unsigned long id, uint64 *data) {
	switch (id) {
	case 0x80040001: return pack_csm_charger_ChargerStatus_0x80040001(o, data);
	case 0x80040002: return pack_csm_charger_ChargerChargingVariable_0x80040002(o, data);
	case 0x80040003: return pack_csm_charger_ChargerChargingService_0x80040003(o, data);
	case 0x80040006: return pack_csm_charger_ChargerDcChargeParameter1_0x80040006(o, data);
	case 0x80040007: return pack_csm_charger_ChargerDcChargeParameter2_0x80040007(o, data);
	case 0x80040008: return pack_csm_charger_ChargerDcDischargeParam_0x80040008(o, data);
	case 0x80040009: return pack_csm_charger_ChargerAcChargeParam_0x80040009(o, data);
	case 0x8004000b: return pack_csm_charger_ChargerAcPresentActivePower_0x8004000b(o, data);
	case 0x8004000c: return pack_csm_charger_ChargerAcTargetActivePower_0x8004000c(o, data);
	case 0x8004000d: return pack_csm_charger_ChargerAcTargetReactivePower_0x8004000d(o, data);
	case 0x8004000e: return pack_csm_charger_ChargerAcMaximumChargePower_0x8004000e(o, data);
	case 0x8004000f: return pack_csm_charger_ChargerAcMinimumChargePower_0x8004000f(o, data);
	case 0x80040010: return pack_csm_charger_ChargerAcMaximumDischargePower_0x80040010(o, data);
	case 0x80040011: return pack_csm_charger_ChargerAcMinimumDischargePower_0x80040011(o, data);
	case 0x80040012: return pack_csm_charger_ChargerAcChargingSafety_0x80040012(o, data);
	case 0x80040020: return pack_csm_charger_ChargerAcFrtLvrt_0x80040020(o, data);
	case 0x80040021: return pack_csm_charger_ChargerAcFrtHvrt_0x80040021(o, data);
	case 0x80040022: return pack_csm_charger_ChargerAcFrtReactivePower_0x80040022(o, data);
	case 0x800401f1: return pack_csm_charger_ChargerDateTime_0x800401f1(o, data);
	default: break; 
	}
	return -1; 
}

